/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostMerchantsRequestNaics: core.serialization.Schema<
    serializers.PostMerchantsRequestNaics.Raw,
    ButtonclikrApi.PostMerchantsRequestNaics
> = core.serialization.enum_([
    "11",
    "21",
    "22",
    "23",
    "31-33",
    "41",
    "44-45",
    "48-49",
    "51",
    "52",
    "53",
    "54",
    "55",
    "56",
    "61",
    "62",
    "71",
    "72",
    "81",
    "91/92",
]);

export declare namespace PostMerchantsRequestNaics {
    type Raw =
        | "11"
        | "21"
        | "22"
        | "23"
        | "31-33"
        | "41"
        | "44-45"
        | "48-49"
        | "51"
        | "52"
        | "53"
        | "54"
        | "55"
        | "56"
        | "61"
        | "62"
        | "71"
        | "72"
        | "81"
        | "91/92";
}
