/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteInvoiceParametersIdResponseResponse } from "./DeleteInvoiceParametersIdResponseResponse";

export const DeleteInvoiceParametersIdResponse: core.serialization.ObjectSchema<
    serializers.DeleteInvoiceParametersIdResponse.Raw,
    ButtonclikrApi.DeleteInvoiceParametersIdResponse
> = core.serialization.object({
    response: DeleteInvoiceParametersIdResponseResponse.optional(),
});

export declare namespace DeleteInvoiceParametersIdResponse {
    interface Raw {
        response?: DeleteInvoiceParametersIdResponseResponse.Raw | null;
    }
}
