/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteInvoiceLineItemsIdResponseResponseDetailsPage } from "./DeleteInvoiceLineItemsIdResponseResponseDetailsPage";

export const DeleteInvoiceLineItemsIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.DeleteInvoiceLineItemsIdResponseResponseDetails.Raw,
    ButtonclikrApi.DeleteInvoiceLineItemsIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: DeleteInvoiceLineItemsIdResponseResponseDetailsPage.optional(),
});

export declare namespace DeleteInvoiceLineItemsIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: DeleteInvoiceLineItemsIdResponseResponseDetailsPage.Raw | null;
    }
}
