/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetInvoiceParametersIdResponseResponseDetails } from "./GetInvoiceParametersIdResponseResponseDetails";

export const GetInvoiceParametersIdResponseResponse: core.serialization.ObjectSchema<
    serializers.GetInvoiceParametersIdResponseResponse.Raw,
    ButtonclikrApi.GetInvoiceParametersIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: GetInvoiceParametersIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetInvoiceParametersIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: GetInvoiceParametersIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
