/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetInvoiceLineItemsIdResponseResponse } from "./GetInvoiceLineItemsIdResponseResponse";

export const GetInvoiceLineItemsIdResponse: core.serialization.ObjectSchema<
    serializers.GetInvoiceLineItemsIdResponse.Raw,
    ButtonclikrApi.GetInvoiceLineItemsIdResponse
> = core.serialization.object({
    response: GetInvoiceLineItemsIdResponseResponse.optional(),
});

export declare namespace GetInvoiceLineItemsIdResponse {
    interface Raw {
        response?: GetInvoiceLineItemsIdResponseResponse.Raw | null;
    }
}
