/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostInvoiceResultsResponseResponseDetails } from "./PostInvoiceResultsResponseResponseDetails";

export const PostInvoiceResultsResponseResponse: core.serialization.ObjectSchema<
    serializers.PostInvoiceResultsResponseResponse.Raw,
    ButtonclikrApi.PostInvoiceResultsResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: PostInvoiceResultsResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PostInvoiceResultsResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: PostInvoiceResultsResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
