/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutInvoiceParametersIdRequestInactive: core.serialization.Schema<
    serializers.PutInvoiceParametersIdRequestInactive.Raw,
    ButtonclikrApi.PutInvoiceParametersIdRequestInactive
> = core.serialization.enum_(["0", "1"]);

export declare namespace PutInvoiceParametersIdRequestInactive {
    type Raw = "0" | "1";
}
