/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutInvoiceParametersIdResponseResponseDetails } from "./PutInvoiceParametersIdResponseResponseDetails";

export const PutInvoiceParametersIdResponseResponse: core.serialization.ObjectSchema<
    serializers.PutInvoiceParametersIdResponseResponse.Raw,
    ButtonclikrApi.PutInvoiceParametersIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: PutInvoiceParametersIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PutInvoiceParametersIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: PutInvoiceParametersIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
