/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutInvoicesIdRequestType: core.serialization.Schema<
    serializers.PutInvoicesIdRequestType.Raw,
    ButtonclikrApi.PutInvoicesIdRequestType
> = core.serialization.enum_(["single", "multiUse", "recurring"]);

export declare namespace PutInvoicesIdRequestType {
    type Raw = "single" | "multiUse" | "recurring";
}
