/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteStatementsIdResponseResponseDetails } from "./DeleteStatementsIdResponseResponseDetails";

export const DeleteStatementsIdResponseResponse: core.serialization.ObjectSchema<
    serializers.DeleteStatementsIdResponseResponse.Raw,
    ButtonclikrApi.DeleteStatementsIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: DeleteStatementsIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace DeleteStatementsIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: DeleteStatementsIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
