/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetSessionsIdResponseResponseDetails } from "./GetSessionsIdResponseResponseDetails";

export const GetSessionsIdResponseResponse: core.serialization.ObjectSchema<
    serializers.GetSessionsIdResponseResponse.Raw,
    ButtonclikrApi.GetSessionsIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: GetSessionsIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetSessionsIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: GetSessionsIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
