/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutStatementsIdResponseResponseDetailsPage } from "./PutStatementsIdResponseResponseDetailsPage";

export const PutStatementsIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.PutStatementsIdResponseResponseDetails.Raw,
    ButtonclikrApi.PutStatementsIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: PutStatementsIdResponseResponseDetailsPage.optional(),
});

export declare namespace PutStatementsIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: PutStatementsIdResponseResponseDetailsPage.Raw | null;
    }
}
