/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ButtonclikrApi from "../../../../index";

/**
 * @example
 *     {
 *         entity: {
 *             "key": "value"
 *         },
 *         serviceName: ButtonclikrApi.PutValueAddedServicesIdRequestServiceName.OmniToken,
 *         isEnabled: ButtonclikrApi.PutValueAddedServicesIdRequestIsEnabled.Zero,
 *         status: {
 *             "key": "value"
 *         },
 *         additionalInformation: {
 *             "key": "value"
 *         },
 *         platform: ButtonclikrApi.PutValueAddedServicesIdRequestPlatform.Apple,
 *         enablementDate: {
 *             "key": "value"
 *         },
 *         valueAddedServicesFlow: {
 *             "key": "value"
 *         },
 *         pciNonValidationFeeEnabled: {
 *             "key": "value"
 *         },
 *         inactive: ButtonclikrApi.PutValueAddedServicesIdRequestInactive.Zero,
 *         frozen: ButtonclikrApi.PutValueAddedServicesIdRequestFrozen.Zero
 *     }
 */
export interface PutValueAddedServicesIdRequest {
    entity?: unknown;
    /** The name of this valueAddedService. */
    serviceName: ButtonclikrApi.PutValueAddedServicesIdRequestServiceName;
    /** This field indicates if the current service is enabled. */
    isEnabled: ButtonclikrApi.PutValueAddedServicesIdRequestIsEnabled;
    status?: unknown;
    additionalInformation?: unknown;
    /** The identifier of the Platform associated with this valueAddedService. */
    platform: ButtonclikrApi.PutValueAddedServicesIdRequestPlatform;
    enablementDate?: unknown;
    valueAddedServicesFlow?: unknown;
    pciNonValidationFeeEnabled?: unknown;
    /** Whether this resource is marked as inactive. */
    inactive: ButtonclikrApi.PutValueAddedServicesIdRequestInactive;
    /** Whether this resource is marked as frozen. */
    frozen: ButtonclikrApi.PutValueAddedServicesIdRequestFrozen;
}
