/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ButtonclikrApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const PutDisbursementEntitiesLogIdRequest: core.serialization.Schema<
    serializers.PutDisbursementEntitiesLogIdRequest.Raw,
    ButtonclikrApi.PutDisbursementEntitiesLogIdRequest
> = core.serialization.object({
    entity: core.serialization.unknown(),
    disbursement: core.serialization.unknown(),
});

export declare namespace PutDisbursementEntitiesLogIdRequest {
    interface Raw {
        entity?: unknown;
        disbursement?: unknown;
    }
}
