/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostReportsRequestFrozen: core.serialization.Schema<
    serializers.PostReportsRequestFrozen.Raw,
    ButtonclikrApi.PostReportsRequestFrozen
> = core.serialization.enum_(["0", "1"]);

export declare namespace PostReportsRequestFrozen {
    type Raw = "0" | "1";
}
