/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ButtonclikrApi from "../../../../index";

/**
 * @example
 *     {
 *         login: {
 *             "key": "value"
 *         },
 *         entity: {
 *             "key": "value"
 *         },
 *         org: {
 *             "key": "value"
 *         },
 *         division: {
 *             "key": "value"
 *         },
 *         partition: {
 *             "key": "value"
 *         },
 *         type: ButtonclikrApi.PutSecretsIdRequestType.BaseKey,
 *         platform: ButtonclikrApi.PutSecretsIdRequestPlatform.Apple,
 *         name: {
 *             "key": "value"
 *         },
 *         description: {
 *             "key": "value"
 *         },
 *         key: {
 *             "key": "value"
 *         },
 *         locked: ButtonclikrApi.PutSecretsIdRequestLocked.Zero,
 *         inactive: ButtonclikrApi.PutSecretsIdRequestInactive.Zero,
 *         frozen: ButtonclikrApi.PutSecretsIdRequestFrozen.Zero
 *     }
 */
export interface PutSecretsIdRequest {
    login?: unknown;
    entity?: unknown;
    org?: unknown;
    division?: unknown;
    partition?: unknown;
    /** The type of secret. Valid Values: baseKey, sftp, publicKey, privateKey, ecPrivateKey, apikey, oldPrivateKey. */
    type: ButtonclikrApi.PutSecretsIdRequestType;
    /**
     * The platform used for the adjustment, this field is required if the adjustment is not between entities.
     *
     * Details:
     */
    platform?: ButtonclikrApi.PutSecretsIdRequestPlatform;
    name?: unknown;
    description?: unknown;
    key?: unknown;
    /** Whether this secret is locked or not, if it is locked then the value of this type of secret will prevail. */
    locked: ButtonclikrApi.PutSecretsIdRequestLocked;
    /** Whether this resource is marked as inactive or not, whether it's marked as active or inactive. */
    inactive: ButtonclikrApi.PutSecretsIdRequestInactive;
    /** Whether this resource is marked as frozen or not frozen. */
    frozen: ButtonclikrApi.PutSecretsIdRequestFrozen;
}
