/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostEntitiesRequestCountry: core.serialization.Schema<
    serializers.PostEntitiesRequestCountry.Raw,
    ButtonclikrApi.PostEntitiesRequestCountry
> = core.serialization.enum_(["USA", "CAN"]);

export declare namespace PostEntitiesRequestCountry {
    type Raw = "USA" | "CAN";
}
