/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutEntitiesIdRequestPendingRiskCheck: core.serialization.Schema<
    serializers.PutEntitiesIdRequestPendingRiskCheck.Raw,
    ButtonclikrApi.PutEntitiesIdRequestPendingRiskCheck
> = core.serialization.enum_(["pending", "successful", "failed", "manual"]);

export declare namespace PutEntitiesIdRequestPendingRiskCheck {
    type Raw = "pending" | "successful" | "failed" | "manual";
}
