/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteNoteDocumentsIdResponseDetailsPage } from "./DeleteNoteDocumentsIdResponseDetailsPage";

export const DeleteNoteDocumentsIdResponseDetails: core.serialization.ObjectSchema<
    serializers.DeleteNoteDocumentsIdResponseDetails.Raw,
    ButtonclikrApi.DeleteNoteDocumentsIdResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: DeleteNoteDocumentsIdResponseDetailsPage.optional(),
});

export declare namespace DeleteNoteDocumentsIdResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: DeleteNoteDocumentsIdResponseDetailsPage.Raw | null;
    }
}
