/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostNoteDocumentsResponseDetailsPage } from "./PostNoteDocumentsResponseDetailsPage";

export const PostNoteDocumentsResponseDetails: core.serialization.ObjectSchema<
    serializers.PostNoteDocumentsResponseDetails.Raw,
    ButtonclikrApi.PostNoteDocumentsResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: PostNoteDocumentsResponseDetailsPage.optional(),
});

export declare namespace PostNoteDocumentsResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: PostNoteDocumentsResponseDetailsPage.Raw | null;
    }
}
