/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostNotesRequestFrozen: core.serialization.Schema<
    serializers.PostNotesRequestFrozen.Raw,
    ButtonclikrApi.PostNotesRequestFrozen
> = core.serialization.enum_(["0", "1"]);

export declare namespace PostNotesRequestFrozen {
    type Raw = "0" | "1";
}
