/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostNotesRequestType: core.serialization.Schema<
    serializers.PostNotesRequestType.Raw,
    ButtonclikrApi.PostNotesRequestType
> = core.serialization.enum_([
    "note",
    "release",
    "review",
    "reReview",
    "amexSales",
    "businessSales",
    "consumerSales",
    "deliverySchedule",
    "immediateDeliveryPercent",
    "sevenDayDeliveryPercent",
    "fourteenDayDeliveryPercent",
    "thirtyDayDeliveryPercent",
    "cardPresentSales",
    "motoSales",
    "ecommerceSales",
    "siteVisit",
    "goodsSold",
    "authorizationFlatFee",
    "capturePercentFee",
    "captureFlatFee",
    "riskApproved",
    "riskPending",
    "riskCancelled",
    "riskDenied",
    "riskClosed",
    "riskInvestigation",
    "riskPendingData",
    "riskFundsReleased",
    "riskActivityApproved",
]);

export declare namespace PostNotesRequestType {
    type Raw =
        | "note"
        | "release"
        | "review"
        | "reReview"
        | "amexSales"
        | "businessSales"
        | "consumerSales"
        | "deliverySchedule"
        | "immediateDeliveryPercent"
        | "sevenDayDeliveryPercent"
        | "fourteenDayDeliveryPercent"
        | "thirtyDayDeliveryPercent"
        | "cardPresentSales"
        | "motoSales"
        | "ecommerceSales"
        | "siteVisit"
        | "goodsSold"
        | "authorizationFlatFee"
        | "capturePercentFee"
        | "captureFlatFee"
        | "riskApproved"
        | "riskPending"
        | "riskCancelled"
        | "riskDenied"
        | "riskClosed"
        | "riskInvestigation"
        | "riskPendingData"
        | "riskFundsReleased"
        | "riskActivityApproved";
}
