/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteConfigurationStagesIdResponseResponseDetails } from "./DeleteConfigurationStagesIdResponseResponseDetails";

export const DeleteConfigurationStagesIdResponseResponse: core.serialization.ObjectSchema<
    serializers.DeleteConfigurationStagesIdResponseResponse.Raw,
    ButtonclikrApi.DeleteConfigurationStagesIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: DeleteConfigurationStagesIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace DeleteConfigurationStagesIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: DeleteConfigurationStagesIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
