/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetConfigurationStagesResponseResponse } from "./GetConfigurationStagesResponseResponse";

export const GetConfigurationStagesResponse: core.serialization.ObjectSchema<
    serializers.GetConfigurationStagesResponse.Raw,
    ButtonclikrApi.GetConfigurationStagesResponse
> = core.serialization.object({
    response: GetConfigurationStagesResponseResponse.optional(),
});

export declare namespace GetConfigurationStagesResponse {
    interface Raw {
        response?: GetConfigurationStagesResponseResponse.Raw | null;
    }
}
