/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetConfigurationsIdResponseResponse } from "./GetConfigurationsIdResponseResponse";

export const GetConfigurationsIdResponse: core.serialization.ObjectSchema<
    serializers.GetConfigurationsIdResponse.Raw,
    ButtonclikrApi.GetConfigurationsIdResponse
> = core.serialization.object({
    response: GetConfigurationsIdResponseResponse.optional(),
});

export declare namespace GetConfigurationsIdResponse {
    interface Raw {
        response?: GetConfigurationsIdResponseResponse.Raw | null;
    }
}
