/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutConfigurationStagesIdRequestInactive: core.serialization.Schema<
    serializers.PutConfigurationStagesIdRequestInactive.Raw,
    ButtonclikrApi.PutConfigurationStagesIdRequestInactive
> = core.serialization.enum_(["0", "1"]);

export declare namespace PutConfigurationStagesIdRequestInactive {
    type Raw = "0" | "1";
}
