/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutConfigurationsIdRequestType: core.serialization.Schema<
    serializers.PutConfigurationsIdRequestType.Raw,
    ButtonclikrApi.PutConfigurationsIdRequestType
> = core.serialization.enum_(["create", "read", "update", "delete"]);

export declare namespace PutConfigurationsIdRequestType {
    type Raw = "create" | "read" | "update" | "delete";
}
