/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetEntityDatasIdResponseResponseDetails } from "./GetEntityDatasIdResponseResponseDetails";

export const GetEntityDatasIdResponseResponse: core.serialization.ObjectSchema<
    serializers.GetEntityDatasIdResponseResponse.Raw,
    ButtonclikrApi.GetEntityDatasIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: GetEntityDatasIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetEntityDatasIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: GetEntityDatasIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
