/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetEntityDatasResponseResponseDetailsPage } from "./GetEntityDatasResponseResponseDetailsPage";

export const GetEntityDatasResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetEntityDatasResponseResponseDetails.Raw,
    ButtonclikrApi.GetEntityDatasResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetEntityDatasResponseResponseDetailsPage.optional(),
});

export declare namespace GetEntityDatasResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetEntityDatasResponseResponseDetailsPage.Raw | null;
    }
}
