/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutEntityDatasIdResponseResponseDetailsPage } from "./PutEntityDatasIdResponseResponseDetailsPage";

export const PutEntityDatasIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.PutEntityDatasIdResponseResponseDetails.Raw,
    ButtonclikrApi.PutEntityDatasIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: PutEntityDatasIdResponseResponseDetailsPage.optional(),
});

export declare namespace PutEntityDatasIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: PutEntityDatasIdResponseResponseDetailsPage.Raw | null;
    }
}
