/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetItemsResponseResponse } from "./GetItemsResponseResponse";

export const GetItemsResponse: core.serialization.ObjectSchema<
    serializers.GetItemsResponse.Raw,
    ButtonclikrApi.GetItemsResponse
> = core.serialization.object({
    response: GetItemsResponseResponse.optional(),
});

export declare namespace GetItemsResponse {
    interface Raw {
        response?: GetItemsResponseResponse.Raw | null;
    }
}
