/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetRefundsResponseResponse } from "./GetRefundsResponseResponse";

export const GetRefundsResponse: core.serialization.ObjectSchema<
    serializers.GetRefundsResponse.Raw,
    ButtonclikrApi.GetRefundsResponse
> = core.serialization.object({
    response: GetRefundsResponseResponse.optional(),
});

export declare namespace GetRefundsResponse {
    interface Raw {
        response?: GetRefundsResponseResponse.Raw | null;
    }
}
