/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetTxnResultsIdResponseResponse } from "./GetTxnResultsIdResponseResponse";

export const GetTxnResultsIdResponse: core.serialization.ObjectSchema<
    serializers.GetTxnResultsIdResponse.Raw,
    ButtonclikrApi.GetTxnResultsIdResponse
> = core.serialization.object({
    response: GetTxnResultsIdResponseResponse.optional(),
});

export declare namespace GetTxnResultsIdResponse {
    interface Raw {
        response?: GetTxnResultsIdResponseResponse.Raw | null;
    }
}
