/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetTxnsIdResponseResponse } from "./GetTxnsIdResponseResponse";

export const GetTxnsIdResponse: core.serialization.ObjectSchema<
    serializers.GetTxnsIdResponse.Raw,
    ButtonclikrApi.GetTxnsIdResponse
> = core.serialization.object({
    response: GetTxnsIdResponseResponse.optional(),
});

export declare namespace GetTxnsIdResponse {
    interface Raw {
        response?: GetTxnsIdResponseResponse.Raw | null;
    }
}
