/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetTerminalTxnsByIdResponseResponse } from "./GetTerminalTxnsByIdResponseResponse";

export const GetTerminalTxnsByIdResponse: core.serialization.ObjectSchema<
    serializers.GetTerminalTxnsByIdResponse.Raw,
    ButtonclikrApi.GetTerminalTxnsByIdResponse
> = core.serialization.object({
    response: GetTerminalTxnsByIdResponseResponse.optional(),
});

export declare namespace GetTerminalTxnsByIdResponse {
    interface Raw {
        response?: GetTerminalTxnsByIdResponseResponse.Raw | null;
    }
}
