/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostHoldsRequestHoldSource: core.serialization.Schema<
    serializers.PostHoldsRequestHoldSource.Raw,
    ButtonclikrApi.PostHoldsRequestHoldSource
> = core.serialization.enum_(["API_DECISION", "POLICY_RUN", "RISK_ALERT", "MANUAL", "ERROR"]);

export declare namespace PostHoldsRequestHoldSource {
    type Raw = "API_DECISION" | "POLICY_RUN" | "RISK_ALERT" | "MANUAL" | "ERROR";
}
