/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutTxnsIdResponseResponse } from "./PutTxnsIdResponseResponse";

export const PutTxnsIdResponse: core.serialization.ObjectSchema<
    serializers.PutTxnsIdResponse.Raw,
    ButtonclikrApi.PutTxnsIdResponse
> = core.serialization.object({
    response: PutTxnsIdResponseResponse.optional(),
});

export declare namespace PutTxnsIdResponse {
    interface Raw {
        response?: PutTxnsIdResponseResponse.Raw | null;
    }
}
