/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const TxnsPostReqBodySchemaModelCofType: core.serialization.Schema<
    serializers.TxnsPostReqBodySchemaModelCofType.Raw,
    ButtonclikrApi.TxnsPostReqBodySchemaModelCofType
> = core.serialization.enum_(["single", "scheduled", "unscheduled"]);

export declare namespace TxnsPostReqBodySchemaModelCofType {
    type Raw = "single" | "scheduled" | "unscheduled";
}
