/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteDecisionRulesIdResponseResponse } from "./DeleteDecisionRulesIdResponseResponse";

export const DeleteDecisionRulesIdResponse: core.serialization.ObjectSchema<
    serializers.DeleteDecisionRulesIdResponse.Raw,
    ButtonclikrApi.DeleteDecisionRulesIdResponse
> = core.serialization.object({
    response: DeleteDecisionRulesIdResponseResponse.optional(),
});

export declare namespace DeleteDecisionRulesIdResponse {
    interface Raw {
        response?: DeleteDecisionRulesIdResponseResponse.Raw | null;
    }
}
