/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutDecisionRulesIdResponseResponse } from "./PutDecisionRulesIdResponseResponse";

export const PutDecisionRulesIdResponse: core.serialization.ObjectSchema<
    serializers.PutDecisionRulesIdResponse.Raw,
    ButtonclikrApi.PutDecisionRulesIdResponse
> = core.serialization.object({
    response: PutDecisionRulesIdResponseResponse.optional(),
});

export declare namespace PutDecisionRulesIdResponse {
    interface Raw {
        response?: PutDecisionRulesIdResponseResponse.Raw | null;
    }
}
