/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetVendorsResponseResponse } from "./GetVendorsResponseResponse";

export const GetVendorsResponse: core.serialization.ObjectSchema<
    serializers.GetVendorsResponse.Raw,
    ButtonclikrApi.GetVendorsResponse
> = core.serialization.object({
    response: GetVendorsResponseResponse.optional(),
});

export declare namespace GetVendorsResponse {
    interface Raw {
        response?: GetVendorsResponseResponse.Raw | null;
    }
}
