/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostVendorsResponseResponse } from "./PostVendorsResponseResponse";

export const PostVendorsResponse: core.serialization.ObjectSchema<
    serializers.PostVendorsResponse.Raw,
    ButtonclikrApi.PostVendorsResponse
> = core.serialization.object({
    response: PostVendorsResponseResponse.optional(),
});

export declare namespace PostVendorsResponse {
    interface Raw {
        response?: PostVendorsResponseResponse.Raw | null;
    }
}
