/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The current status of the settlement.
 */
export type PostSettlementsRequestStatus = "cancelled" | "failed" | "pending" | "processed" | "processing";

export const PostSettlementsRequestStatus = {
    Cancelled: "cancelled",
    Failed: "failed",
    Pending: "pending",
    Processed: "processed",
    Processing: "processing",
} as const;
