/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { Trip } from "../../../types/Trip";
import { GetTripsResponseLinks } from "./GetTripsResponseLinks";

export const GetTripsResponse: core.serialization.ObjectSchema<
    serializers.GetTripsResponse.Raw,
    ButtonclikrApi.GetTripsResponse
> = core.serialization.object({
    data: core.serialization.list(Trip).optional(),
    links: GetTripsResponseLinks.optional(),
});

export declare namespace GetTripsResponse {
    interface Raw {
        data?: Trip.Raw[] | null;
        links?: GetTripsResponseLinks.Raw | null;
    }
}
