/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The name of this configuration resource.
 */
export type PostConfigurationsRequestName =
    | "account"
    | "batchTxn"
    | "binReport"
    | "board"
    | "chargeback"
    | "decision"
    | "decisionBoard"
    | "decisionTxn"
    | "echeckTxn"
    | "encryption"
    | "omnitoken"
    | "onlineTxn"
    | "onlineTxnSocket"
    | "paymentUpdates"
    | "payout"
    | "payoutCredit"
    | "payoutDebit"
    | "plaid"
    | "reports"
    | "register"
    | "saferPayment"
    | "unregister"
    | "varsheetRetrieval"
    | "watchlist";

export const PostConfigurationsRequestName = {
    Account: "account",
    BatchTxn: "batchTxn",
    BinReport: "binReport",
    Board: "board",
    Chargeback: "chargeback",
    Decision: "decision",
    DecisionBoard: "decisionBoard",
    DecisionTxn: "decisionTxn",
    EcheckTxn: "echeckTxn",
    Encryption: "encryption",
    Omnitoken: "omnitoken",
    OnlineTxn: "onlineTxn",
    OnlineTxnSocket: "onlineTxnSocket",
    PaymentUpdates: "paymentUpdates",
    Payout: "payout",
    PayoutCredit: "payoutCredit",
    PayoutDebit: "payoutDebit",
    Plaid: "plaid",
    Reports: "reports",
    Register: "register",
    SaferPayment: "saferPayment",
    Unregister: "unregister",
    VarsheetRetrieval: "varsheetRetrieval",
    Watchlist: "watchlist",
} as const;
