/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The integration associated with this configuration resource.
 */
export type PutConfigurationsIdRequestIntegration =
    | "ACH"
    | "APPLE"
    | "ELAVON"
    | "FEDACH"
    | "FIRSTDATA"
    | "LEGITSCRIPT"
    | "NEUTRINO"
    | "OFAC"
    | "OMNITOKEN"
    | "bigbux"
    | "PLAID"
    | "PUSHY"
    | "SAFERPAYMENT"
    | "SIFT"
    | "SOCURE"
    | "SOUNDPAYMENTS"
    | "TDBANK"
    | "TDBANKCA"
    | "VANTIV"
    | "VCORE"
    | "WEBSHIELD"
    | "WELLSACH"
    | "WELLSFARGO"
    | "WFSINGLE"
    | "WORLDPAY";

export const PutConfigurationsIdRequestIntegration = {
    Ach: "ACH",
    Apple: "APPLE",
    Elavon: "ELAVON",
    Fedach: "FEDACH",
    Firstdata: "FIRSTDATA",
    Legitscript: "LEGITSCRIPT",
    Neutrino: "NEUTRINO",
    Ofac: "OFAC",
    Omnitoken: "OMNITOKEN",
    Bigbux: "bigbux",
    Plaid: "PLAID",
    Pushy: "PUSHY",
    Saferpayment: "SAFERPAYMENT",
    Sift: "SIFT",
    Socure: "SOCURE",
    Soundpayments: "SOUNDPAYMENTS",
    Tdbank: "TDBANK",
    Tdbankca: "TDBANKCA",
    Vantiv: "VANTIV",
    Vcore: "VCORE",
    Webshield: "WEBSHIELD",
    Wellsach: "WELLSACH",
    Wellsfargo: "WELLSFARGO",
    Wfsingle: "WFSINGLE",
    Worldpay: "WORLDPAY",
} as const;
