/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetSubscriptionsIdResponseDetailsPage } from "./GetSubscriptionsIdResponseDetailsPage";

export const GetSubscriptionsIdResponseDetails: core.serialization.ObjectSchema<
    serializers.GetSubscriptionsIdResponseDetails.Raw,
    ButtonclikrApi.GetSubscriptionsIdResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetSubscriptionsIdResponseDetailsPage.optional(),
});

export declare namespace GetSubscriptionsIdResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetSubscriptionsIdResponseDetailsPage.Raw | null;
    }
}
