/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetSubscriptionsIdResponseResponseDetails } from "./GetSubscriptionsIdResponseResponseDetails";

export const GetSubscriptionsIdResponseResponse: core.serialization.ObjectSchema<
    serializers.GetSubscriptionsIdResponseResponse.Raw,
    ButtonclikrApi.GetSubscriptionsIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: GetSubscriptionsIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetSubscriptionsIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: GetSubscriptionsIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
