/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostPlansRequestUm: core.serialization.Schema<
    serializers.PostPlansRequestUm.Raw,
    ButtonclikrApi.PostPlansRequestUm
> = core.serialization.enum_(["actual", "percent"]);

export declare namespace PostPlansRequestUm {
    type Raw = "actual" | "percent";
}
