/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostPlansRequestInactive: core.serialization.Schema<
    serializers.PostPlansRequestInactive.Raw,
    ButtonclikrApi.PostPlansRequestInactive
> = core.serialization.enum_(["0", "1"]);

export declare namespace PostPlansRequestInactive {
    type Raw = "0" | "1";
}
