/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutPlansIdRequestUm: core.serialization.Schema<
    serializers.PutPlansIdRequestUm.Raw,
    ButtonclikrApi.PutPlansIdRequestUm
> = core.serialization.enum_(["actual", "percent"]);

export declare namespace PutPlansIdRequestUm {
    type Raw = "actual" | "percent";
}
