/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether the terminal should print a receipt or not.
 *
 * <details>
 * <summary>Valid Values</summary>
 *
 * - `noReceipt` - **No Receipt.**
 *
 * - `merchant` - **Merchant copy only.**
 *
 * - `customer` - **Customer copy only.**
 *
 * - `both` - **Merchant and Customer copy.**
 *
 * </details>
 */
export type TerminalTxnsPostReqBodySchemaModelReceipt = "noReceipt" | "merchant" | "customer" | "both";

export const TerminalTxnsPostReqBodySchemaModelReceipt = {
    NoReceipt: "noReceipt",
    Merchant: "merchant",
    Customer: "customer",
    Both: "both",
} as const;
