/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetRevShareSchedulesIdResponseResponse } from "./GetRevShareSchedulesIdResponseResponse";

export const GetRevShareSchedulesIdResponse: core.serialization.ObjectSchema<
    serializers.GetRevShareSchedulesIdResponse.Raw,
    ButtonclikrApi.GetRevShareSchedulesIdResponse
> = core.serialization.object({
    response: GetRevShareSchedulesIdResponseResponse.optional(),
});

export declare namespace GetRevShareSchedulesIdResponse {
    interface Raw {
        response?: GetRevShareSchedulesIdResponseResponse.Raw | null;
    }
}
