/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutRevShareSchedulesIdResponseResponse } from "./PutRevShareSchedulesIdResponseResponse";

export const PutRevShareSchedulesIdResponse: core.serialization.ObjectSchema<
    serializers.PutRevShareSchedulesIdResponse.Raw,
    ButtonclikrApi.PutRevShareSchedulesIdResponse
> = core.serialization.object({
    response: PutRevShareSchedulesIdResponseResponse.optional(),
});

export declare namespace PutRevShareSchedulesIdResponse {
    interface Raw {
        response?: PutRevShareSchedulesIdResponseResponse.Raw | null;
    }
}
