/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutRevShareSchedulesIdRequestInactive: core.serialization.Schema<
    serializers.PutRevShareSchedulesIdRequestInactive.Raw,
    ButtonclikrApi.PutRevShareSchedulesIdRequestInactive
> = core.serialization.enum_(["0", "1"]);

export declare namespace PutRevShareSchedulesIdRequestInactive {
    type Raw = "0" | "1";
}
