/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ButtonclikrApi from "../../../../index";

/**
 * @example
 *     {
 *         report: {
 *             "key": "value"
 *         },
 *         documentType: ButtonclikrApi.PostReportResultsRequestDocumentType.Json,
 *         status: ButtonclikrApi.PostReportResultsRequestStatus.Pending,
 *         effective: {
 *             "key": "value"
 *         },
 *         inactive: ButtonclikrApi.PostReportResultsRequestInactive.Zero,
 *         frozen: ButtonclikrApi.PostReportResultsRequestFrozen.Zero
 *     }
 */
export interface PostReportResultsRequest {
    report?: unknown;
    /**
     * The report results data format type.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     *   - `json` - **JSON data format.**
     *
     *   - `xml` - **XML data format.**
     *
     *   - `soap` - **SOAP data format.**
     *  </details>
     *
     */
    documentType: ButtonclikrApi.PostReportResultsRequestDocumentType;
    /**
     * Report Results Status
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     *   - `pending` - **Report Results Pending.**
     *
     *   - `processed` - **Report Results Complete.**
     *
     * </details>
     *
     */
    status: ButtonclikrApi.PostReportResultsRequestStatus;
    effective?: unknown;
    /** Whether this resource is marked as inactive. Valid Values: `0` - Active, `1` - Inactive. */
    inactive: ButtonclikrApi.PostReportResultsRequestInactive;
    /** Whether this resource is marked as frozen. Valid Values: `0` - Not Frozen, `1` - Frozen. */
    frozen: ButtonclikrApi.PostReportResultsRequestFrozen;
}
