/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostTeamLoginsRequestRead = "0" | "1";

export const PostTeamLoginsRequestRead = {
    Zero: "0",
    One: "1",
} as const;
