/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Update rights for this Login on this Team.
 */
export type PutTeamLoginsIdRequestUpdate = "0" | "1";

export const PutTeamLoginsIdRequestUpdate = {
    Zero: "0",
    One: "1",
} as const;
