/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether this resource is marked as inactive or not, whether it's marked as 0 (Active) or 1 (Inactive).
 */
export type PutTeamsIdRequestInactive = "0" | "1";

export const PutTeamsIdRequestInactive = {
    Zero: "0",
    One: "1",
} as const;
