/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of business using the terminal.
 *
 * <details>
 * <summary>Valid Values</summary>
 *
 * - `1` - **Retail**
 * - `2` - **Retail (with tips).**
 * - `3` - **Restaurant**
 * - `4` - **Lodging**
 * - `5` - **Bar**
 * - `6` - **Cash Advance**
 * - `7` - **Mail / Telephone Order.**
 * - `8` - **Pay-at-the-Pump**
 * - `9` - **Service / Rest Station.**
 * - `10` - **eCommerce**
 * - `11` - **Direct Marketing**
 * - `12` - **Fine Dining**
 * - `13` - **Gift Card-Only**
 *
 * </details>
 */
export type PostTerminalsRequestEnvironment =
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "11"
    | "12"
    | "13";

export const PostTerminalsRequestEnvironment = {
    One: "1",
    Two: "2",
    Three: "3",
    Four: "4",
    Five: "5",
    Six: "6",
    Seven: "7",
    Eight: "8",
    Nine: "9",
    Ten: "10",
    Eleven: "11",
    Twelve: "12",
    Thirteen: "13",
} as const;
