/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates whether the Member is the 'primary' contact for the associated Merchant, and only one Member associated with each Merchant can be the 'primary' Member; this field takes a value of `0`, indicating Not Primary contact, or `1`, indicating Primary contact.
 */
export type PostMembersRequestPrimary = "0" | "1";

export const PostMembersRequestPrimary = {
    Zero: "0",
    One: "1",
} as const;
