/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteSecretsIdResponseResponse } from "./DeleteSecretsIdResponseResponse";
import { DeleteSecretsIdResponseDetails } from "./DeleteSecretsIdResponseDetails";

export const DeleteSecretsIdResponse: core.serialization.ObjectSchema<
    serializers.DeleteSecretsIdResponse.Raw,
    ButtonclikrApi.DeleteSecretsIdResponse
> = core.serialization.object({
    response: DeleteSecretsIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: DeleteSecretsIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace DeleteSecretsIdResponse {
    interface Raw {
        response?: DeleteSecretsIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: DeleteSecretsIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
