/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetSecretsResponseResponseDetailsPage } from "./GetSecretsResponseResponseDetailsPage";

export const GetSecretsResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetSecretsResponseResponseDetails.Raw,
    ButtonclikrApi.GetSecretsResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetSecretsResponseResponseDetailsPage.optional(),
});

export declare namespace GetSecretsResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetSecretsResponseResponseDetailsPage.Raw | null;
    }
}
