/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetSecretsIdResponseResponseDetailsPage } from "./GetSecretsIdResponseResponseDetailsPage";

export const GetSecretsIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetSecretsIdResponseResponseDetails.Raw,
    ButtonclikrApi.GetSecretsIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetSecretsIdResponseResponseDetailsPage.optional(),
});

export declare namespace GetSecretsIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetSecretsIdResponseResponseDetailsPage.Raw | null;
    }
}
