/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutSecretsIdRequestType: core.serialization.Schema<
    serializers.PutSecretsIdRequestType.Raw,
    ButtonclikrApi.PutSecretsIdRequestType
> = core.serialization.enum_(["baseKey", "sftp", "publicKey", "privateKey", "ecPrivateKey", "apikey", "oldPrivateKey"]);

export declare namespace PutSecretsIdRequestType {
    type Raw = "baseKey" | "sftp" | "publicKey" | "privateKey" | "ecPrivateKey" | "apikey" | "oldPrivateKey";
}
