/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutMccsIdResponseResponse } from "./PutMccsIdResponseResponse";

export const PutMccsIdResponse: core.serialization.ObjectSchema<
    serializers.PutMccsIdResponse.Raw,
    ButtonclikrApi.PutMccsIdResponse
> = core.serialization.object({
    response: PutMccsIdResponseResponse.optional(),
});

export declare namespace PutMccsIdResponse {
    interface Raw {
        response?: PutMccsIdResponseResponse.Raw | null;
    }
}
