/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutFundingParametersIdRequestValue: core.serialization.Schema<
    serializers.PutFundingParametersIdRequestValue.Raw,
    ButtonclikrApi.PutFundingParametersIdRequestValue
> = core.serialization.enum_(["0", "1"]);

export declare namespace PutFundingParametersIdRequestValue {
    type Raw = "0" | "1";
}
