/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostEntityRoutesResponseResponseDetailsPage } from "./PostEntityRoutesResponseResponseDetailsPage";

export const PostEntityRoutesResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.PostEntityRoutesResponseResponseDetails.Raw,
    ButtonclikrApi.PostEntityRoutesResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: PostEntityRoutesResponseResponseDetailsPage.optional(),
});

export declare namespace PostEntityRoutesResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: PostEntityRoutesResponseResponseDetailsPage.Raw | null;
    }
}
