/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteReportItemsIdResponseDetailsPage } from "./DeleteReportItemsIdResponseDetailsPage";

export const DeleteReportItemsIdResponseDetails: core.serialization.ObjectSchema<
    serializers.DeleteReportItemsIdResponseDetails.Raw,
    ButtonclikrApi.DeleteReportItemsIdResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: DeleteReportItemsIdResponseDetailsPage.optional(),
});

export declare namespace DeleteReportItemsIdResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: DeleteReportItemsIdResponseDetailsPage.Raw | null;
    }
}
