/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteReportItemsIdResponseResponse } from "./DeleteReportItemsIdResponseResponse";
import { DeleteReportItemsIdResponseDetails } from "./DeleteReportItemsIdResponseDetails";

export const DeleteReportItemsIdResponse: core.serialization.ObjectSchema<
    serializers.DeleteReportItemsIdResponse.Raw,
    ButtonclikrApi.DeleteReportItemsIdResponse
> = core.serialization.object({
    response: DeleteReportItemsIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: DeleteReportItemsIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace DeleteReportItemsIdResponse {
    interface Raw {
        response?: DeleteReportItemsIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: DeleteReportItemsIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
