/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetVerificationResultsResponseResponse } from "./GetVerificationResultsResponseResponse";

export const GetVerificationResultsResponse: core.serialization.ObjectSchema<
    serializers.GetVerificationResultsResponse.Raw,
    ButtonclikrApi.GetVerificationResultsResponse
> = core.serialization.object({
    response: GetVerificationResultsResponseResponse.optional(),
});

export declare namespace GetVerificationResultsResponse {
    interface Raw {
        response?: GetVerificationResultsResponseResponse.Raw | null;
    }
}
