/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteParametersIdResponseResponseDetails } from "./DeleteParametersIdResponseResponseDetails";

export const DeleteParametersIdResponseResponse: core.serialization.ObjectSchema<
    serializers.DeleteParametersIdResponseResponse.Raw,
    ButtonclikrApi.DeleteParametersIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: DeleteParametersIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace DeleteParametersIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: DeleteParametersIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
