/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteParametersIdResponseResponseDetailsPage } from "./DeleteParametersIdResponseResponseDetailsPage";

export const DeleteParametersIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.DeleteParametersIdResponseResponseDetails.Raw,
    ButtonclikrApi.DeleteParametersIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: DeleteParametersIdResponseResponseDetailsPage.optional(),
});

export declare namespace DeleteParametersIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: DeleteParametersIdResponseResponseDetailsPage.Raw | null;
    }
}
