/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostParametersRequestFundingEnabled: core.serialization.Schema<
    serializers.PostParametersRequestFundingEnabled.Raw,
    ButtonclikrApi.PostParametersRequestFundingEnabled
> = core.serialization.enum_(["0", "1"]);

export declare namespace PostParametersRequestFundingEnabled {
    type Raw = "0" | "1";
}
