/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostParametersRequestSameDayPayoutsEnabled: core.serialization.Schema<
    serializers.PostParametersRequestSameDayPayoutsEnabled.Raw,
    ButtonclikrApi.PostParametersRequestSameDayPayoutsEnabled
> = core.serialization.enum_(["0", "1"]);

export declare namespace PostParametersRequestSameDayPayoutsEnabled {
    type Raw = "0" | "1";
}
