/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostParametersRequestPositiveBalanceEmail: core.serialization.Schema<
    serializers.PostParametersRequestPositiveBalanceEmail.Raw,
    ButtonclikrApi.PostParametersRequestPositiveBalanceEmail
> = core.serialization.enum_(["0", "1"]);

export declare namespace PostParametersRequestPositiveBalanceEmail {
    type Raw = "0" | "1";
}
