/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteProfitSharesIdResponseResponse } from "./DeleteProfitSharesIdResponseResponse";
import { DeleteProfitSharesIdResponseDetails } from "./DeleteProfitSharesIdResponseDetails";

export const DeleteProfitSharesIdResponse: core.serialization.ObjectSchema<
    serializers.DeleteProfitSharesIdResponse.Raw,
    ButtonclikrApi.DeleteProfitSharesIdResponse
> = core.serialization.object({
    response: DeleteProfitSharesIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: DeleteProfitSharesIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace DeleteProfitSharesIdResponse {
    interface Raw {
        response?: DeleteProfitSharesIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: DeleteProfitSharesIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
