/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetEntityDebtsResponseDetailsPage } from "./GetEntityDebtsResponseDetailsPage";

export const GetEntityDebtsResponseDetails: core.serialization.ObjectSchema<
    serializers.GetEntityDebtsResponseDetails.Raw,
    ButtonclikrApi.GetEntityDebtsResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetEntityDebtsResponseDetailsPage.optional(),
});

export declare namespace GetEntityDebtsResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetEntityDebtsResponseDetailsPage.Raw | null;
    }
}
