/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetEntityReservesIdResponseResponseDetailsPage } from "./GetEntityReservesIdResponseResponseDetailsPage";

export const GetEntityReservesIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetEntityReservesIdResponseResponseDetails.Raw,
    ButtonclikrApi.GetEntityReservesIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetEntityReservesIdResponseResponseDetailsPage.optional(),
});

export declare namespace GetEntityReservesIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetEntityReservesIdResponseResponseDetailsPage.Raw | null;
    }
}
