/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetProfitShareResultsIdResponseResponse } from "./GetProfitShareResultsIdResponseResponse";
import { GetProfitShareResultsIdResponseDetails } from "./GetProfitShareResultsIdResponseDetails";

export const GetProfitShareResultsIdResponse: core.serialization.ObjectSchema<
    serializers.GetProfitShareResultsIdResponse.Raw,
    ButtonclikrApi.GetProfitShareResultsIdResponse
> = core.serialization.object({
    response: GetProfitShareResultsIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: GetProfitShareResultsIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetProfitShareResultsIdResponse {
    interface Raw {
        response?: GetProfitShareResultsIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: GetProfitShareResultsIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
