/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetProfitSharesIdResponseResponseDetails } from "./GetProfitSharesIdResponseResponseDetails";

export const GetProfitSharesIdResponseResponse: core.serialization.ObjectSchema<
    serializers.GetProfitSharesIdResponseResponse.Raw,
    ButtonclikrApi.GetProfitSharesIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: GetProfitSharesIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetProfitSharesIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: GetProfitSharesIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
