/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetProfitSharesIdResponseResponseDetailsPage } from "./GetProfitSharesIdResponseResponseDetailsPage";

export const GetProfitSharesIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetProfitSharesIdResponseResponseDetails.Raw,
    ButtonclikrApi.GetProfitSharesIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetProfitSharesIdResponseResponseDetailsPage.optional(),
});

export declare namespace GetProfitSharesIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetProfitSharesIdResponseResponseDetailsPage.Raw | null;
    }
}
