/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetProfitShareRulesIdResponseResponseDetails } from "./GetProfitShareRulesIdResponseResponseDetails";

export const GetProfitShareRulesIdResponseResponse: core.serialization.ObjectSchema<
    serializers.GetProfitShareRulesIdResponseResponse.Raw,
    ButtonclikrApi.GetProfitShareRulesIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: GetProfitShareRulesIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetProfitShareRulesIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: GetProfitShareRulesIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
