/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostEntityReturnsRequestFrozen: core.serialization.Schema<
    serializers.PostEntityReturnsRequestFrozen.Raw,
    ButtonclikrApi.PostEntityReturnsRequestFrozen
> = core.serialization.enum_(["0", "1"]);

export declare namespace PostEntityReturnsRequestFrozen {
    type Raw = "0" | "1";
}
