/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostProfitSharesResponseResponseDetailsPage } from "./PostProfitSharesResponseResponseDetailsPage";

export const PostProfitSharesResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.PostProfitSharesResponseResponseDetails.Raw,
    ButtonclikrApi.PostProfitSharesResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: PostProfitSharesResponseResponseDetailsPage.optional(),
});

export declare namespace PostProfitSharesResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: PostProfitSharesResponseResponseDetailsPage.Raw | null;
    }
}
