/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostEntityReturnsResponseResponse } from "./PostEntityReturnsResponseResponse";

export const PostEntityReturnsResponse: core.serialization.ObjectSchema<
    serializers.PostEntityReturnsResponse.Raw,
    ButtonclikrApi.PostEntityReturnsResponse
> = core.serialization.object({
    response: PostEntityReturnsResponseResponse.optional(),
});

export declare namespace PostEntityReturnsResponse {
    interface Raw {
        response?: PostEntityReturnsResponseResponse.Raw | null;
    }
}
