/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostEntityReservesResponseResponse } from "./PostEntityReservesResponseResponse";
import { PostEntityReservesResponseDetails } from "./PostEntityReservesResponseDetails";

export const PostEntityReservesResponse: core.serialization.ObjectSchema<
    serializers.PostEntityReservesResponse.Raw,
    ButtonclikrApi.PostEntityReservesResponse
> = core.serialization.object({
    response: PostEntityReservesResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: PostEntityReservesResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PostEntityReservesResponse {
    interface Raw {
        response?: PostEntityReservesResponseResponse.Raw | null;
        data?: unknown | null;
        details?: PostEntityReservesResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
