/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostEntityReturnsResponseResponseDetailsPage } from "./PostEntityReturnsResponseResponseDetailsPage";

export const PostEntityReturnsResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.PostEntityReturnsResponseResponseDetails.Raw,
    ButtonclikrApi.PostEntityReturnsResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: PostEntityReturnsResponseResponseDetailsPage.optional(),
});

export declare namespace PostEntityReturnsResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: PostEntityReturnsResponseResponseDetailsPage.Raw | null;
    }
}
