/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutProfitShareRulesIdResponseResponseDetails } from "./PutProfitShareRulesIdResponseResponseDetails";

export const PutProfitShareRulesIdResponseResponse: core.serialization.ObjectSchema<
    serializers.PutProfitShareRulesIdResponseResponse.Raw,
    ButtonclikrApi.PutProfitShareRulesIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: PutProfitShareRulesIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PutProfitShareRulesIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: PutProfitShareRulesIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
