/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ButtonclikrApi from "../../../../index";

/**
 * @example
 *     {
 *         billing: {
 *             "key": "value"
 *         },
 *         event: ButtonclikrApi.PutBillingEventsIdRequestEvent.Fees,
 *         eventSchedule: {
 *             "key": "value"
 *         },
 *         deductFromBalance: ButtonclikrApi.PutBillingEventsIdRequestDeductFromBalance.Zero,
 *         inactive: ButtonclikrApi.PutBillingEventsIdRequestInactive.Zero,
 *         frozen: ButtonclikrApi.PutBillingEventsIdRequestFrozen.Zero
 *     }
 */
export interface PutBillingEventsIdRequest {
    billing?: unknown;
    /**
     * The type of event that triggers billing.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     *   - `fees` - **Fee.** Fee events trigger the billing configuration.
     *
     *   - `chargebacks` - **Chargebacks.** Chargeback events trigger the billing configuration.
     *
     *   - `returns` - **Returns.** Return events trigger the billing configuration.
     *
     *   - `profitShares` - **Profit Shares.** Profit Sharing events trigger the billing configuration.
     *
     * </details>
     *
     */
    event: ButtonclikrApi.PutBillingEventsIdRequestEvent;
    eventSchedule?: unknown;
    /**
     * Whether to deduct the billing amount from the entity's account balance.
     *
     * <details>
     *   <summary>Valid Values</summary>
     *
     *   - `0` - **Do not deduct from balance.**
     *
     *   - `1` - **Deduct from balance.**
     *   </details>
     *
     */
    deductFromBalance: ButtonclikrApi.PutBillingEventsIdRequestDeductFromBalance;
    /**
     * Whether this resource is marked as inactive.
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     *
     * - `1` - **Inactive**
     * </details>
     *
     */
    inactive: ButtonclikrApi.PutBillingEventsIdRequestInactive;
    /**
     * Whether this resource is marked as frozen.
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     *
     * - `1` - **Frozen**
     * </details>
     *
     */
    frozen: ButtonclikrApi.PutBillingEventsIdRequestFrozen;
}
