/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether this resource is marked as inactive.
 */
export type PutCurrencyRatesIdRequestInactive = "0" | "1";

export const PutCurrencyRatesIdRequestInactive = {
    Zero: "0",
    One: "1",
} as const;
