/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostParametersRequestDiscoverAcquiredEnabled = "0" | "1";

export const PostParametersRequestDiscoverAcquiredEnabled = {
    Zero: "0",
    One: "1",
} as const;
