/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether debtRepayment for transactions is enabled.
 * The default setting is 0.
 */
export type PostParametersRequestDebtRepaymentEnabled = "0" | "1";

export const PostParametersRequestDebtRepaymentEnabled = {
    Zero: "0",
    One: "1",
} as const;
