/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Email notification to the business email when an existing bank account record is updated.
 */
export type PutParametersIdRequestBankAccountUpdateStopEmail = "0" | "1";

export const PutParametersIdRequestBankAccountUpdateStopEmail = {
    Zero: "0",
    One: "1",
} as const;
