/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Will dictate whether an email is sent when an entity recovers from a negative balance.
 * The default setting is 0.
 */
export type PutParametersIdRequestPositiveBalanceEmail = "0" | "1";

export const PutParametersIdRequestPositiveBalanceEmail = {
    Zero: "0",
    One: "1",
} as const;
