/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PutParametersIdRequestLoginAsEnabled = "0" | "1";

export const PutParametersIdRequestLoginAsEnabled = {
    Zero: "0",
    One: "1",
} as const;
