/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether all tokenized payments will be checked for updates. Tokenized payments will be checked and updated if enabled.
 * The default setting is 0.
 */
export type PutParametersIdRequestUpdateAllTokensEnabled = "0" | "1";

export const PutParametersIdRequestUpdateAllTokensEnabled = {
    Zero: "0",
    One: "1",
} as const;
