/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether American Express OptBlue should be enabled.
 * The default setting is '0'.
 */
export type PutParametersIdRequestOptBlueEnabled = "0" | "1";

export const PutParametersIdRequestOptBlueEnabled = {
    Zero: "0",
    One: "1",
} as const;
