/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether FinCen boarding exemptions should be disabled.
 * The default setting is '0'.
 */
export type PutParametersIdRequestBoardingExemptionsDisabled = "0" | "1";

export const PutParametersIdRequestBoardingExemptionsDisabled = {
    Zero: "0",
    One: "1",
} as const;
