/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ButtonclikrApi from "../../../../index";

/**
 * @example
 *     {
 *         name: {
 *             "key": "value"
 *         },
 *         description: {
 *             "key": "value"
 *         },
 *         token: ButtonclikrApi.PutApikeysIdRequestToken.Zero,
 *         inactive: ButtonclikrApi.PutApikeysIdRequestInactive.Zero,
 *         frozen: ButtonclikrApi.PutApikeysIdRequestFrozen.Zero
 *     }
 */
export interface PutApikeysIdRequest {
    name?: unknown;
    description?: unknown;
    /**
     * Whether or not an AuthToken is required as part of the authentication when this Apikey is used.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **The authToken mechanism is disabled.**
     *
     * - `1` - **The authToken mechanism is required for 'POST' and 'DELETE' requests.**
     *
     * </details>
     *
     */
    token: ButtonclikrApi.PutApikeysIdRequestToken;
    /**
     * Whether this resource is marked as inactive.
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     *
     * - `1` - **Inactive**
     * </details>
     *
     */
    inactive: ButtonclikrApi.PutApikeysIdRequestInactive;
    /**
     * Whether this resource is marked as frozen.
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     *
     * - `1` - **Frozen**
     * </details>
     *
     */
    frozen: ButtonclikrApi.PutApikeysIdRequestFrozen;
}
