/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostPartitionsRequestNoHoldEmail: core.serialization.Schema<
    serializers.PostPartitionsRequestNoHoldEmail.Raw,
    ButtonclikrApi.PostPartitionsRequestNoHoldEmail
> = core.serialization.enum_(["0", "1"]);

export declare namespace PostPartitionsRequestNoHoldEmail {
    type Raw = "0" | "1";
}
