/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutPartitionsIdRequestNoHoldEmail: core.serialization.Schema<
    serializers.PutPartitionsIdRequestNoHoldEmail.Raw,
    ButtonclikrApi.PutPartitionsIdRequestNoHoldEmail
> = core.serialization.enum_(["0", "1"]);

export declare namespace PutPartitionsIdRequestNoHoldEmail {
    type Raw = "0" | "1";
}
