/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ButtonclikrApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { PostTeamLoginsRequestCreate } from "../../types/PostTeamLoginsRequestCreate";
import { PostTeamLoginsRequestRead } from "../../types/PostTeamLoginsRequestRead";
import { PostTeamLoginsRequestUpdate } from "../../types/PostTeamLoginsRequestUpdate";
import { PostTeamLoginsRequestDelete } from "../../types/PostTeamLoginsRequestDelete";
import { PostTeamLoginsRequestReference } from "../../types/PostTeamLoginsRequestReference";
import { PostTeamLoginsRequestTeamAdmin } from "../../types/PostTeamLoginsRequestTeamAdmin";

export const PostTeamLoginsRequest: core.serialization.Schema<
    serializers.PostTeamLoginsRequest.Raw,
    ButtonclikrApi.PostTeamLoginsRequest
> = core.serialization.object({
    login: core.serialization.unknown(),
    team: core.serialization.unknown(),
    create: PostTeamLoginsRequestCreate,
    read: PostTeamLoginsRequestRead,
    update: PostTeamLoginsRequestUpdate,
    delete: PostTeamLoginsRequestDelete,
    reference: PostTeamLoginsRequestReference,
    teamAdmin: PostTeamLoginsRequestTeamAdmin,
});

export declare namespace PostTeamLoginsRequest {
    interface Raw {
        login?: unknown;
        team?: unknown;
        create: PostTeamLoginsRequestCreate.Raw;
        read: PostTeamLoginsRequestRead.Raw;
        update: PostTeamLoginsRequestUpdate.Raw;
        delete: PostTeamLoginsRequestDelete.Raw;
        reference: PostTeamLoginsRequestReference.Raw;
        teamAdmin: PostTeamLoginsRequestTeamAdmin.Raw;
    }
}
