/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ButtonclikrApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { PutTeamLoginsIdRequestCreate } from "../../types/PutTeamLoginsIdRequestCreate";
import { PutTeamLoginsIdRequestRead } from "../../types/PutTeamLoginsIdRequestRead";
import { PutTeamLoginsIdRequestUpdate } from "../../types/PutTeamLoginsIdRequestUpdate";
import { PutTeamLoginsIdRequestDelete } from "../../types/PutTeamLoginsIdRequestDelete";
import { PutTeamLoginsIdRequestReference } from "../../types/PutTeamLoginsIdRequestReference";
import { PutTeamLoginsIdRequestTeamAdmin } from "../../types/PutTeamLoginsIdRequestTeamAdmin";

export const PutTeamLoginsIdRequest: core.serialization.Schema<
    serializers.PutTeamLoginsIdRequest.Raw,
    ButtonclikrApi.PutTeamLoginsIdRequest
> = core.serialization.object({
    login: core.serialization.unknown(),
    team: core.serialization.unknown(),
    create: PutTeamLoginsIdRequestCreate,
    read: PutTeamLoginsIdRequestRead,
    update: PutTeamLoginsIdRequestUpdate,
    delete: PutTeamLoginsIdRequestDelete,
    reference: PutTeamLoginsIdRequestReference,
    teamAdmin: PutTeamLoginsIdRequestTeamAdmin,
});

export declare namespace PutTeamLoginsIdRequest {
    interface Raw {
        login?: unknown;
        team?: unknown;
        create: PutTeamLoginsIdRequestCreate.Raw;
        read: PutTeamLoginsIdRequestRead.Raw;
        update: PutTeamLoginsIdRequestUpdate.Raw;
        delete: PutTeamLoginsIdRequestDelete.Raw;
        reference: PutTeamLoginsIdRequestReference.Raw;
        teamAdmin: PutTeamLoginsIdRequestTeamAdmin.Raw;
    }
}
