/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostPartitionsRequestChangeManagementEnabled = "0" | "1";

export const PostPartitionsRequestChangeManagementEnabled = {
    Zero: "0",
    One: "1",
} as const;
