/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether to disable the email address confirmation process for this Partition.
 */
export type PostPartitionsRequestNoEmailConfirmation = "0" | "1";

export const PostPartitionsRequestNoEmailConfirmation = {
    Zero: "0",
    One: "1",
} as const;
