/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ButtonclikrApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { PutWatchlistsIdRequestIntegration } from "../../types/PutWatchlistsIdRequestIntegration";
import { PutWatchlistsIdRequestDefault } from "../../types/PutWatchlistsIdRequestDefault";
import { PutWatchlistsIdRequestInactive } from "../../types/PutWatchlistsIdRequestInactive";
import { PutWatchlistsIdRequestFrozen } from "../../types/PutWatchlistsIdRequestFrozen";

export const PutWatchlistsIdRequest: core.serialization.Schema<
    serializers.PutWatchlistsIdRequest.Raw,
    ButtonclikrApi.PutWatchlistsIdRequest
> = core.serialization.object({
    login: core.serialization.unknown(),
    integration: PutWatchlistsIdRequestIntegration.optional(),
    name: core.serialization.unknown().optional(),
    description: core.serialization.unknown().optional(),
    default: PutWatchlistsIdRequestDefault,
    custom: core.serialization.unknown().optional(),
    inactive: PutWatchlistsIdRequestInactive,
    frozen: PutWatchlistsIdRequestFrozen,
});

export declare namespace PutWatchlistsIdRequest {
    interface Raw {
        login?: unknown;
        integration?: PutWatchlistsIdRequestIntegration.Raw | null;
        name?: unknown | null;
        description?: unknown | null;
        default: PutWatchlistsIdRequestDefault.Raw;
        custom?: unknown | null;
        inactive: PutWatchlistsIdRequestInactive.Raw;
        frozen: PutWatchlistsIdRequestFrozen.Raw;
    }
}
