/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ButtonclikrApi from "../../../index";

export interface CreateBookingResponse extends ButtonclikrApi.Booking {
    links?: ButtonclikrApi.LinksSelf;
}
