/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetTerminalRefsResponseResponseDetails } from "./GetTerminalRefsResponseResponseDetails";

export const GetTerminalRefsResponseResponse: core.serialization.ObjectSchema<
    serializers.GetTerminalRefsResponseResponse.Raw,
    ButtonclikrApi.GetTerminalRefsResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: GetTerminalRefsResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetTerminalRefsResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: GetTerminalRefsResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
