/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetTerminalsIdResponseResponseDetails } from "./GetTerminalsIdResponseResponseDetails";

export const GetTerminalsIdResponseResponse: core.serialization.ObjectSchema<
    serializers.GetTerminalsIdResponseResponse.Raw,
    ButtonclikrApi.GetTerminalsIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: GetTerminalsIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetTerminalsIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: GetTerminalsIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
