/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutTerminalsIdResponseResponseDetails } from "./PutTerminalsIdResponseResponseDetails";

export const PutTerminalsIdResponseResponse: core.serialization.ObjectSchema<
    serializers.PutTerminalsIdResponseResponse.Raw,
    ButtonclikrApi.PutTerminalsIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: PutTerminalsIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PutTerminalsIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: PutTerminalsIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
