/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutEntityCustomFieldsIdResponseResponseDetails } from "./PutEntityCustomFieldsIdResponseResponseDetails";

export const PutEntityCustomFieldsIdResponseResponse: core.serialization.ObjectSchema<
    serializers.PutEntityCustomFieldsIdResponseResponse.Raw,
    ButtonclikrApi.PutEntityCustomFieldsIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: PutEntityCustomFieldsIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PutEntityCustomFieldsIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: PutEntityCustomFieldsIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
