/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetAdjustmentsResponseResponseDetailsPage } from "./GetAdjustmentsResponseResponseDetailsPage";

export const GetAdjustmentsResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetAdjustmentsResponseResponseDetails.Raw,
    ButtonclikrApi.GetAdjustmentsResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetAdjustmentsResponseResponseDetailsPage.optional(),
});

export declare namespace GetAdjustmentsResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetAdjustmentsResponseResponseDetailsPage.Raw | null;
    }
}
