/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetEntriesResponseDetailsPage } from "./GetEntriesResponseDetailsPage";

export const GetEntriesResponseDetails: core.serialization.ObjectSchema<
    serializers.GetEntriesResponseDetails.Raw,
    ButtonclikrApi.GetEntriesResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetEntriesResponseDetailsPage.optional(),
});

export declare namespace GetEntriesResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetEntriesResponseDetailsPage.Raw | null;
    }
}
