/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetEntriesIdResponseResponseDetails } from "./GetEntriesIdResponseResponseDetails";

export const GetEntriesIdResponseResponse: core.serialization.ObjectSchema<
    serializers.GetEntriesIdResponseResponse.Raw,
    ButtonclikrApi.GetEntriesIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: GetEntriesIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetEntriesIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: GetEntriesIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
