/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetMerchantResultsIdResponseResponseDetailsPage } from "./GetMerchantResultsIdResponseResponseDetailsPage";

export const GetMerchantResultsIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetMerchantResultsIdResponseResponseDetails.Raw,
    ButtonclikrApi.GetMerchantResultsIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetMerchantResultsIdResponseResponseDetailsPage.optional(),
});

export declare namespace GetMerchantResultsIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetMerchantResultsIdResponseResponseDetailsPage.Raw | null;
    }
}
