/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostCurrencyRatesResponseResponseDetailsPage } from "./PostCurrencyRatesResponseResponseDetailsPage";

export const PostCurrencyRatesResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.PostCurrencyRatesResponseResponseDetails.Raw,
    ButtonclikrApi.PostCurrencyRatesResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: PostCurrencyRatesResponseResponseDetailsPage.optional(),
});

export declare namespace PostCurrencyRatesResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: PostCurrencyRatesResponseResponseDetailsPage.Raw | null;
    }
}
