/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether this resource is marked as inactive. Valid Values: `0` - Active, `1` - Inactive.
 */
export type PostFeeRulesRequestInactive = "0" | "1";

export const PostFeeRulesRequestInactive = {
    Zero: "0",
    One: "1",
} as const;
