/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The unit of measure for this Fee is The unit of measure for this Fee. Notes: Percentage and Surcharge units will only apply to Fee schedules set to trigger from monetary events, such as an authorization, capture, or refund. - `1` - **Percentage**. The Fee is a percentage of the related event amount, specified in the 'amount' field in basis points. - `2` - **Fixed Amount**. The Fee is a fixed amount, specified in the 'amount' field as an integer in cents. - `3` - **Surcharge**. The Fee is a percentage of the related event amount as a surcharge (the calculated amount will be based on the assumption that the related event amount already contains the fee amount in it), specified in the 'amount' field in basis points.
 */
export type PostFeesRequestUm = "1" | "2" | "3";

export const PostFeesRequestUm = {
    One: "1",
    Two: "2",
    Three: "3",
} as const;
