/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicator to extract fee from txn supplied fee. When set, the amount will correspond to the fee amount in the txn and only that amount will be extractable; anything over that amount will not be extracted. Valid Values: `0` - Disabled, fee will be calculated normally; `1` - Enabled, fee will be calculated based on transaction fee.
 */
export type PostFeesRequestTxnFee = "0" | "1";

export const PostFeesRequestTxnFee = {
    Zero: "0",
    One: "1",
} as const;
