/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of Transaction. Valid Values: `1` - Credit Card Only: Sale Transaction, processes a sale and charges the customer; `2` - Credit Card Only: Auth Transaction, authorizes and holds the requested total on the credit card; `3` - Credit Card Only: Capture Transaction, finalizes a prior Auth Transaction and charges the customer; `4` - Credit Card Only: Reverse Authorization, reverses a prior Auth or Sale Transaction and releases the credit hold; `5` - Credit Card Only: Refund Transaction, refunds a prior Capture or Sale Transaction (total may be specified for a partial refund); `7` - Echeck Only: Echeck Sale Transaction, sale transaction for ECheck payment; `8` - Echeck Only: ECheck Refund Transaction, refund transaction for prior ECheck Sale Transaction; `11` - Echeck Only: Echeck Redeposit Transaction, attempt to redeposit a prior failed eCheck Sale Transaction; `12` - Echeck Only: Echeck Account Verification Transaction, attempt to verify eCheck payment details.
 */
export type PostFeeRulesRequestType =
    | "less"
    | "equal"
    | "notEqual"
    | "greater"
    | "swiped"
    | "signed"
    | "type"
    | "origin"
    | "method"
    | "interchange"
    | "cvvResult"
    | "avsResult"
    | "3dsResult"
    | "mcc"
    | "merchantCountry"
    | "issuerCountry"
    | "international"
    | "platform"
    | "methodType"
    | "emv"
    | "misuse"
    | "bin"
    | "fundingCurrencyEqual"
    | "fundingCurrencyNotEqual"
    | "fundingCurrencyMismatch"
    | "fundingEnabled"
    | "settledCurrencyMismatch"
    | "status";

export const PostFeeRulesRequestType = {
    Less: "less",
    Equal: "equal",
    NotEqual: "notEqual",
    Greater: "greater",
    Swiped: "swiped",
    Signed: "signed",
    Type: "type",
    Origin: "origin",
    Method: "method",
    Interchange: "interchange",
    CvvResult: "cvvResult",
    AvsResult: "avsResult",
    ThreeDsResult: "3dsResult",
    Mcc: "mcc",
    MerchantCountry: "merchantCountry",
    IssuerCountry: "issuerCountry",
    International: "international",
    Platform: "platform",
    MethodType: "methodType",
    Emv: "emv",
    Misuse: "misuse",
    Bin: "bin",
    FundingCurrencyEqual: "fundingCurrencyEqual",
    FundingCurrencyNotEqual: "fundingCurrencyNotEqual",
    FundingCurrencyMismatch: "fundingCurrencyMismatch",
    FundingEnabled: "fundingEnabled",
    SettledCurrencyMismatch: "settledCurrencyMismatch",
    Status: "status",
} as const;
