/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of third-party assessed fees.
 *
 * <details>
 * <summary>Valid Values</summary>
 *
 * - FANF - Visa Fixed Acquirer Network Fee (FanF)
 *
 * - MCLOCATION - Mastercard Merchant Location Fee
 *
 * - VISAINTEGRITY - Visa Transaction Integrity Fee (TIF)
 *
 * </details>
 */
export type PutExternalFeesIdRequestType =
    | "FANF"
    | "MCLOCATION"
    | "VISAINTEGRITY"
    | "VALUTEC_DIGITAL_GIFT_PLUS_PACKAGE"
    | "VALUTEC_DIGITAL_GIFT_PLUS_PACKAGE_TXN"
    | "VALUTEC_DIGITAL_GIFT_PLUS_PACKAGE_ME"
    | "VALUTEC_LOYALTY_PLUS_PACKAGE"
    | "VALUTEC_LOYALTY_PLUS_PACKAGE_TXN"
    | "VALUTEC_ESSENTIAL_GIFT"
    | "VALUTEC_ESSENTIAL_MONTHLY_TXN"
    | "VALUTEC_TRANSACTION_FEE"
    | "VALUTEC_GIFT_ACH_POOLING"
    | "VALUTEC_MAINTENANCE_FEE"
    | "VALUTEC_SETUP_FEE"
    | "VALUTEC_JUMP_START_KIT"
    | "VALUTEC_LAUNCH_BOX_KIT"
    | "VALUTEC_500_CUSTOM_CARDS"
    | "SAFERPAYMENTS_BASIC"
    | "SAFERPAYMENTS_MANAGED"
    | "SAFERPAYMENTS_PCI_NONVALIDATION"
    | "OMNITOKEN"
    | "NPT_REVBOOST_EMBEDDED_TMS_MONTHLY"
    | "NPT_REVBOOST_EMBEDDED_TMS_PPT"
    | "INTERCHANGE";

export const PutExternalFeesIdRequestType = {
    Fanf: "FANF",
    Mclocation: "MCLOCATION",
    Visaintegrity: "VISAINTEGRITY",
    ValutecDigitalGiftPlusPackage: "VALUTEC_DIGITAL_GIFT_PLUS_PACKAGE",
    ValutecDigitalGiftPlusPackageTxn: "VALUTEC_DIGITAL_GIFT_PLUS_PACKAGE_TXN",
    ValutecDigitalGiftPlusPackageMe: "VALUTEC_DIGITAL_GIFT_PLUS_PACKAGE_ME",
    ValutecLoyaltyPlusPackage: "VALUTEC_LOYALTY_PLUS_PACKAGE",
    ValutecLoyaltyPlusPackageTxn: "VALUTEC_LOYALTY_PLUS_PACKAGE_TXN",
    ValutecEssentialGift: "VALUTEC_ESSENTIAL_GIFT",
    ValutecEssentialMonthlyTxn: "VALUTEC_ESSENTIAL_MONTHLY_TXN",
    ValutecTransactionFee: "VALUTEC_TRANSACTION_FEE",
    ValutecGiftAchPooling: "VALUTEC_GIFT_ACH_POOLING",
    ValutecMaintenanceFee: "VALUTEC_MAINTENANCE_FEE",
    ValutecSetupFee: "VALUTEC_SETUP_FEE",
    ValutecJumpStartKit: "VALUTEC_JUMP_START_KIT",
    ValutecLaunchBoxKit: "VALUTEC_LAUNCH_BOX_KIT",
    Valutec500CustomCards: "VALUTEC_500_CUSTOM_CARDS",
    SaferpaymentsBasic: "SAFERPAYMENTS_BASIC",
    SaferpaymentsManaged: "SAFERPAYMENTS_MANAGED",
    SaferpaymentsPciNonvalidation: "SAFERPAYMENTS_PCI_NONVALIDATION",
    Omnitoken: "OMNITOKEN",
    NptRevboostEmbeddedTmsMonthly: "NPT_REVBOOST_EMBEDDED_TMS_MONTHLY",
    NptRevboostEmbeddedTmsPpt: "NPT_REVBOOST_EMBEDDED_TMS_PPT",
    Interchange: "INTERCHANGE",
} as const;
