/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Applies the fee based on the volume of a resource, applying it to the total amount of all transactions (1), or the total amount of all transactions per entity EIN/tax ID (2) or per merchant (3).
 *
 * <details>
 * <summary>Valid Values</summary>
 *
 * - `1` - **Txn.** The total amount of all transactions.
 *
 * - `2` - **Txn-TaxID.** The total amount of all transactions per entity EIN/tax ID.
 *
 * - `3` - **Txn-Merchant.** The total amount of all transactions per entity.
 *
 * </details>
 */
export type PutFeesIdRequestCollection = "1" | "2" | "3";

export const PutFeesIdRequestCollection = {
    One: "1",
    Two: "2",
    Three: "3",
} as const;
