/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of the fee is a standard fee or a third-party platform fee.
 */
export type PutFeesIdRequestType = "1" | "2";

export const PutFeesIdRequestType = {
    One: "1",
    Two: "2",
} as const;
