/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Where the action defined by this DecisionAction should apply
 */
export type PutDecisionsIdRequestApplication = "account" | "txn" | "entity";

export const PutDecisionsIdRequestApplication = {
    Account: "account",
    Txn: "txn",
    Entity: "entity",
} as const;
