/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The target that this decision should apply at.
 */
export type PutDecisionsIdRequestTarget =
    | "activation"
    | "auth"
    | "postauth"
    | "capture"
    | "refund"
    | "createEntity"
    | "underwriting"
    | "preboard"
    | "postboard"
    | "txn"
    | "txnVolume"
    | "payout"
    | "payoutVolume";

export const PutDecisionsIdRequestTarget = {
    Activation: "activation",
    Auth: "auth",
    Postauth: "postauth",
    Capture: "capture",
    Refund: "refund",
    CreateEntity: "createEntity",
    Underwriting: "underwriting",
    Preboard: "preboard",
    Postboard: "postboard",
    Txn: "txn",
    TxnVolume: "txnVolume",
    Payout: "payout",
    PayoutVolume: "payoutVolume",
} as const;
