/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ButtonclikrApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { PutNotesIdRequestType } from "../../types/PutNotesIdRequestType";
import { PutNotesIdRequestInactive } from "../../types/PutNotesIdRequestInactive";
import { PutNotesIdRequestFrozen } from "../../types/PutNotesIdRequestFrozen";

export const PutNotesIdRequest: core.serialization.Schema<
    serializers.PutNotesIdRequest.Raw,
    ButtonclikrApi.PutNotesIdRequest
> = core.serialization.object({
    login: core.serialization.unknown(),
    txn: core.serialization.unknown().optional(),
    terminalTxn: core.serialization.unknown().optional(),
    hold: core.serialization.unknown().optional(),
    entity: core.serialization.unknown().optional(),
    type: PutNotesIdRequestType,
    data: core.serialization.unknown(),
    note: core.serialization.unknown().optional(),
    inactive: PutNotesIdRequestInactive,
    frozen: PutNotesIdRequestFrozen,
});

export declare namespace PutNotesIdRequest {
    interface Raw {
        login?: unknown;
        txn?: unknown | null;
        terminalTxn?: unknown | null;
        hold?: unknown | null;
        entity?: unknown | null;
        type: PutNotesIdRequestType.Raw;
        data?: unknown;
        note?: unknown | null;
        inactive: PutNotesIdRequestInactive.Raw;
        frozen: PutNotesIdRequestFrozen.Raw;
    }
}
