/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeletePaymentUpdateGroupsIdResponseResponseDetailsPage } from "./DeletePaymentUpdateGroupsIdResponseResponseDetailsPage";

export const DeletePaymentUpdateGroupsIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.DeletePaymentUpdateGroupsIdResponseResponseDetails.Raw,
    ButtonclikrApi.DeletePaymentUpdateGroupsIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: DeletePaymentUpdateGroupsIdResponseResponseDetailsPage.optional(),
});

export declare namespace DeletePaymentUpdateGroupsIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: DeletePaymentUpdateGroupsIdResponseResponseDetailsPage.Raw | null;
    }
}
