/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetPaymentUpdatesResponseResponseDetailsPage } from "./GetPaymentUpdatesResponseResponseDetailsPage";

export const GetPaymentUpdatesResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetPaymentUpdatesResponseResponseDetails.Raw,
    ButtonclikrApi.GetPaymentUpdatesResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetPaymentUpdatesResponseResponseDetailsPage.optional(),
});

export declare namespace GetPaymentUpdatesResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetPaymentUpdatesResponseResponseDetailsPage.Raw | null;
    }
}
