/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetTokensResponseResponse } from "./GetTokensResponseResponse";
import { GetTokensResponseDetails } from "./GetTokensResponseDetails";

export const GetTokensResponse: core.serialization.ObjectSchema<
    serializers.GetTokensResponse.Raw,
    ButtonclikrApi.GetTokensResponse
> = core.serialization.object({
    response: GetTokensResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: GetTokensResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetTokensResponse {
    interface Raw {
        response?: GetTokensResponseResponse.Raw | null;
        data?: unknown | null;
        details?: GetTokensResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
