/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostTokensRequestType: core.serialization.Schema<
    serializers.PostTokensRequestType.Raw,
    ButtonclikrApi.PostTokensRequestType
> = core.serialization.enum_(["omnitoken", "networktoken", "internal"]);

export declare namespace PostTokensRequestType {
    type Raw = "omnitoken" | "networktoken" | "internal";
}
