/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutTokensIdResponseResponse } from "./PutTokensIdResponseResponse";
import { PutTokensIdResponseDetails } from "./PutTokensIdResponseDetails";

export const PutTokensIdResponse: core.serialization.ObjectSchema<
    serializers.PutTokensIdResponse.Raw,
    ButtonclikrApi.PutTokensIdResponse
> = core.serialization.object({
    response: PutTokensIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: PutTokensIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PutTokensIdResponse {
    interface Raw {
        response?: PutTokensIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: PutTokensIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
