/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether this resource is marked as frozen.
 */
export type PostChargebacksRequestFrozen = "0" | "1";

export const PostChargebacksRequestFrozen = {
    Zero: "0",
    One: "1",
} as const;
