/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteReservesIdResponseResponseDetails } from "./DeleteReservesIdResponseResponseDetails";

export const DeleteReservesIdResponseResponse: core.serialization.ObjectSchema<
    serializers.DeleteReservesIdResponseResponse.Raw,
    ButtonclikrApi.DeleteReservesIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: DeleteReservesIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace DeleteReservesIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: DeleteReservesIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
