/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutReservesIdRequestLevel: core.serialization.Schema<
    serializers.PutReservesIdRequestLevel.Raw,
    ButtonclikrApi.PutReservesIdRequestLevel
> = core.serialization.enum_(["admin", "division", "merchant", "partition"]);

export declare namespace PutReservesIdRequestLevel {
    type Raw = "admin" | "division" | "merchant" | "partition";
}
