/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetHostsIdResponseResponseDetails } from "./GetHostsIdResponseResponseDetails";

export const GetHostsIdResponseResponse: core.serialization.ObjectSchema<
    serializers.GetHostsIdResponseResponse.Raw,
    ButtonclikrApi.GetHostsIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: GetHostsIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetHostsIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: GetHostsIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
