/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetHostsResponseResponse } from "./GetHostsResponseResponse";

export const GetHostsResponse: core.serialization.ObjectSchema<
    serializers.GetHostsResponse.Raw,
    ButtonclikrApi.GetHostsResponse
> = core.serialization.object({
    response: GetHostsResponseResponse.optional(),
});

export declare namespace GetHostsResponse {
    interface Raw {
        response?: GetHostsResponseResponse.Raw | null;
    }
}
