/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutHostsIdRequestInactive: core.serialization.Schema<
    serializers.PutHostsIdRequestInactive.Raw,
    ButtonclikrApi.PutHostsIdRequestInactive
> = core.serialization.enum_(["0", "1"]);

export declare namespace PutHostsIdRequestInactive {
    type Raw = "0" | "1";
}
