/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ButtonclikrApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { PostVerificationsRequestType } from "../../types/PostVerificationsRequestType";
import { PostVerificationsRequestGenerated } from "../../types/PostVerificationsRequestGenerated";

export const PostVerificationsRequest: core.serialization.Schema<
    serializers.PostVerificationsRequest.Raw,
    ButtonclikrApi.PostVerificationsRequest
> = core.serialization.object({
    login: core.serialization.unknown(),
    entity: core.serialization.unknown().optional(),
    member: core.serialization.unknown().optional(),
    txn: core.serialization.unknown().optional(),
    terminalTxn: core.serialization.unknown().optional(),
    account: core.serialization.unknown().optional(),
    decision: core.serialization.unknown(),
    type: PostVerificationsRequestType,
    level: core.serialization.unknown(),
    fromCache: core.serialization.unknown().optional(),
    additionalOptions: core.serialization.unknown().optional(),
    options: core.serialization.unknown().optional(),
    value: core.serialization.unknown(),
    score: core.serialization.unknown().optional(),
    description: core.serialization.unknown().optional(),
    ref: core.serialization.unknown().optional(),
    generated: PostVerificationsRequestGenerated,
});

export declare namespace PostVerificationsRequest {
    interface Raw {
        login?: unknown;
        entity?: unknown | null;
        member?: unknown | null;
        txn?: unknown | null;
        terminalTxn?: unknown | null;
        account?: unknown | null;
        decision?: unknown;
        type: PostVerificationsRequestType.Raw;
        level?: unknown;
        fromCache?: unknown | null;
        additionalOptions?: unknown | null;
        options?: unknown | null;
        value?: unknown;
        score?: unknown | null;
        description?: unknown | null;
        ref?: unknown | null;
        generated: PostVerificationsRequestGenerated.Raw;
    }
}
