/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteRequestTokensIdResponseResponse } from "./DeleteRequestTokensIdResponseResponse";

export const DeleteRequestTokensIdResponse: core.serialization.ObjectSchema<
    serializers.DeleteRequestTokensIdResponse.Raw,
    ButtonclikrApi.DeleteRequestTokensIdResponse
> = core.serialization.object({
    response: DeleteRequestTokensIdResponseResponse.optional(),
});

export declare namespace DeleteRequestTokensIdResponse {
    interface Raw {
        response?: DeleteRequestTokensIdResponseResponse.Raw | null;
    }
}
