/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetRequestTokensResponseResponseDetailsPage } from "./GetRequestTokensResponseResponseDetailsPage";

export const GetRequestTokensResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetRequestTokensResponseResponseDetails.Raw,
    ButtonclikrApi.GetRequestTokensResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetRequestTokensResponseResponseDetailsPage.optional(),
});

export declare namespace GetRequestTokensResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetRequestTokensResponseResponseDetailsPage.Raw | null;
    }
}
