/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetMessagesResponseResponseDetailsPage } from "./GetMessagesResponseResponseDetailsPage";

export const GetMessagesResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetMessagesResponseResponseDetails.Raw,
    ButtonclikrApi.GetMessagesResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetMessagesResponseResponseDetailsPage.optional(),
});

export declare namespace GetMessagesResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetMessagesResponseResponseDetailsPage.Raw | null;
    }
}
