/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteMappingsIdResponseResponseDetailsPage } from "./DeleteMappingsIdResponseResponseDetailsPage";

export const DeleteMappingsIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.DeleteMappingsIdResponseResponseDetails.Raw,
    ButtonclikrApi.DeleteMappingsIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: DeleteMappingsIdResponseResponseDetailsPage.optional(),
});

export declare namespace DeleteMappingsIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: DeleteMappingsIdResponseResponseDetailsPage.Raw | null;
    }
}
