/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ButtonclikrApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const PostEntityReservesRequest: core.serialization.Schema<
    serializers.PostEntityReservesRequest.Raw,
    ButtonclikrApi.PostEntityReservesRequest
> = core.serialization.object({
    login: core.serialization.unknown(),
    fund: core.serialization.unknown(),
    total: core.serialization.unknown(),
    name: core.serialization.unknown().optional(),
    description: core.serialization.unknown().optional(),
});

export declare namespace PostEntityReservesRequest {
    interface Raw {
        login?: unknown;
        fund?: unknown;
        total?: unknown;
        name?: unknown | null;
        description?: unknown | null;
    }
}
