/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ButtonclikrApi from "../../../../index";

/**
 * @example
 *     {
 *         account: 1,
 *         name: "TD Bank",
 *         primary: 1,
 *         type: ButtonclikrApi.AccountsUpdateReqBodySchemaType.All,
 *         status: 1,
 *         reserved: 1,
 *         inactive: 1,
 *         frozen: 1
 *     }
 */
export interface AccountsUpdateReqBodySchema {
    /** An object representing details of the Account, including the type of Account (method), Account number and routing code. */
    account: number;
    /**
     * A client-supplied name for this bank account.
     * This field is stored as a text string and must be between 0 and 100 characters long.
     */
    name?: string;
    /**
     * A client-supplied description for this bank account.
     * This field is stored as a text string and must be between 0 and 100 characters long.
     */
    description?: string;
    /** Indicates whether the Account is the 'primary' Account for the associated Entity. Only one Account associated with each Entity can be the 'primary' Account. */
    primary: number;
    /**
     * The type of financial account, debit, credit or both.
     *
     *   <details>
     *   <summary>Valid Values</summary>
     *
     *     - `all` - Debit/Checking + Credit
     *
     *     - `credit` - Credit-Only
     *
     *     - `debit` - Debit/Checking-Only
     *
     *   </details>
     *
     */
    type: ButtonclikrApi.AccountsUpdateReqBodySchemaType;
    /**
     * The status of the Account is ready to be verified.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Ready.**
     *
     * - `1` - **Ready.**
     *
     * - `2` - **Challenged.**
     *
     * - `3` - **Verified.**
     *
     * - `4` - **Manual.**
     *
     * </details>
     *
     */
    status: number;
    /**
     * Indicates whether the Account is reserved and the action that will be taken as a result, which can have valid values of `0`, `1`, or `3` for No reserve, Account withheld, or Account usage pending manual review respectively, or `4` to Move all funds from this Account into a reserve.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **No reserve.**
     *
     * - `1` - **Ready.**
     *
     * - `2` - **Account withheld.**
     *
     * - `3` - **Account usage pending manual review.**
     *
     * - `4` - **Move all funds from this Account into a reserve.**
     *
     * </details>
     *
     */
    reserved: number;
    /** The last stage completed for risk assessment. */
    checkStage?: "createAccount";
    /** The expiration date of the related debit account in MMYY format, for example, '0118' for January, 2018 or '0225' for February, 2025. */
    expiration?: string;
    /** The account number mask, showing the last 4 digits of the account number. */
    mask?: string;
    inactive: ButtonclikrApi.Inactive;
    frozen: ButtonclikrApi.Frozen;
}
