/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetPayoutFlowsResponseResponse } from "./GetPayoutFlowsResponseResponse";

export const GetPayoutFlowsResponse: core.serialization.ObjectSchema<
    serializers.GetPayoutFlowsResponse.Raw,
    ButtonclikrApi.GetPayoutFlowsResponse
> = core.serialization.object({
    response: GetPayoutFlowsResponseResponse.optional(),
});

export declare namespace GetPayoutFlowsResponse {
    interface Raw {
        response?: GetPayoutFlowsResponseResponse.Raw | null;
    }
}
