/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutPayoutsIdResponseResponse } from "./PutPayoutsIdResponseResponse";

export const PutPayoutsIdResponse: core.serialization.ObjectSchema<
    serializers.PutPayoutsIdResponse.Raw,
    ButtonclikrApi.PutPayoutsIdResponse
> = core.serialization.object({
    response: PutPayoutsIdResponseResponse.optional(),
});

export declare namespace PutPayoutsIdResponse {
    interface Raw {
        response?: PutPayoutsIdResponseResponse.Raw | null;
    }
}
