/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ButtonclikrApi from "../../../index";

export interface PutOrgsIdResponse {
    response?: ButtonclikrApi.PutOrgsIdResponseResponse;
    data?: unknown;
    /** An object describing the response, including the request ID and pagination indicators. */
    details?: ButtonclikrApi.PutOrgsIdResponseDetails;
    errors?: unknown;
}
