/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether this API key should have access to only public resources. Public resources include Transactions, Tokens, Customers, and Items. All other resources are private. Valid Values: `0` - Session can also access private resources, `1` - Session can only access public resources.
 */
export type PostApikeysRequestPublic = "0" | "1";

export const PostApikeysRequestPublic = {
    Zero: "0",
    One: "1",
} as const;
