/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetDisbursementResultsIdResponseResponse } from "./GetDisbursementResultsIdResponseResponse";

export const GetDisbursementResultsIdResponse: core.serialization.ObjectSchema<
    serializers.GetDisbursementResultsIdResponse.Raw,
    ButtonclikrApi.GetDisbursementResultsIdResponse
> = core.serialization.object({
    response: GetDisbursementResultsIdResponseResponse.optional(),
});

export declare namespace GetDisbursementResultsIdResponse {
    interface Raw {
        response?: GetDisbursementResultsIdResponseResponse.Raw | null;
    }
}
