/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ButtonclikrApi from "../../../../index";

/**
 * @example
 *     {
 *         entity: {
 *             "key": "value"
 *         },
 *         division: {
 *             "key": "value"
 *         },
 *         inactive: ButtonclikrApi.PutVendorsIdRequestInactive.Zero,
 *         frozen: ButtonclikrApi.PutVendorsIdRequestFrozen.Zero
 *     }
 */
export interface PutVendorsIdRequest {
    entity?: unknown;
    division?: unknown;
    /** Whether this resource is marked as inactive or not. */
    inactive: ButtonclikrApi.PutVendorsIdRequestInactive;
    /** Whether this resource is marked as frozen or not frozen. */
    frozen: ButtonclikrApi.PutVendorsIdRequestFrozen;
}
