/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ButtonclikrApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { PostEntityRoutesRequestPlatform } from "../../types/PostEntityRoutesRequestPlatform";
import { PostEntityRoutesRequestCurrency } from "../../types/PostEntityRoutesRequestCurrency";
import { PostEntityRoutesRequestFundingCurrency } from "../../types/PostEntityRoutesRequestFundingCurrency";
import { Inactive } from "../../../../types/Inactive";
import { Frozen } from "../../../../types/Frozen";

export const PostEntityRoutesRequest: core.serialization.Schema<
    serializers.PostEntityRoutesRequest.Raw,
    ButtonclikrApi.PostEntityRoutesRequest
> = core.serialization.object({
    login: core.serialization.string(),
    division: core.serialization.string().optional(),
    entity: core.serialization.string().optional(),
    org: core.serialization.string().optional(),
    partition: core.serialization.string().optional(),
    platform: PostEntityRoutesRequestPlatform,
    currency: PostEntityRoutesRequestCurrency.optional(),
    fundingCurrency: PostEntityRoutesRequestFundingCurrency.optional(),
    options: core.serialization.string().optional(),
    default: core.serialization.number(),
    inactive: Inactive,
    frozen: Frozen,
});

export declare namespace PostEntityRoutesRequest {
    interface Raw {
        login: string;
        division?: string | null;
        entity?: string | null;
        org?: string | null;
        partition?: string | null;
        platform: PostEntityRoutesRequestPlatform.Raw;
        currency?: PostEntityRoutesRequestCurrency.Raw | null;
        fundingCurrency?: PostEntityRoutesRequestFundingCurrency.Raw | null;
        options?: string | null;
        default: number;
        inactive: Inactive.Raw;
        frozen: Frozen.Raw;
    }
}
