/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the requested change.
 */
export type ChangeRequestModelStatus = "pending" | "manualReview" | "approved" | "declined";

export const ChangeRequestModelStatus = {
    Pending: "pending",
    ManualReview: "manualReview",
    Approved: "approved",
    Declined: "declined",
} as const;
