/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The U.S. state associated with this Entity.
 * Valid values are any U.S. state's 2 character postal abbreviation.
 */
export type EntityResponseModelState =
    | "AB"
    | "BC"
    | "MB"
    | "NB"
    | "NL"
    | "NT"
    | "NS"
    | "NU"
    | "true"
    | "PE"
    | "QC"
    | "SK"
    | "YT";

export const EntityResponseModelState = {
    Ab: "AB",
    Bc: "BC",
    Mb: "MB",
    Nb: "NB",
    Nl: "NL",
    Nt: "NT",
    Ns: "NS",
    Nu: "NU",
    True: "true",
    Pe: "PE",
    Qc: "QC",
    Sk: "SK",
    Yt: "YT",
} as const;
