/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MerchantResponseModelGooglePayActive = "0" | "1";

export const MerchantResponseModelGooglePayActive = {
    Zero: "0",
    One: "1",
} as const;
