/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The event on the Org or Entity that should trigger the creation of an associated Payout resource.
 *
 * <details>
 * <summary>Valid Values</summary>
 *
 * - `accountCreate` - Primary payment account creation (primary must be 1)
 *
 * - `board` - Merchant boarding
 *
 *  </details>
 */
export type PayoutFlowsRequestModelTrigger = "accountCreate" | "board";

export const PayoutFlowsRequestModelTrigger = {
    AccountCreate: "accountCreate",
    Board: "board",
} as const;
