/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The unit of measure for this Payout is the percentage of funds, and if the Entity has a negative balance of $10 and the amount is set to 10000 (100%), then $10 will be drawn from their account to fully replenish the balance to $0. <details> <summary>Valid Values</summary> - `percent` - **Percentage unit measurement.** (Percentage of Funds). - `actual` - **Actual unit measurement.** (Exact Currency Amount). - `percentneg` - **Negative Percentage unit measurement.** (Replenish account by percent negative back to $0). </details>
 */
export type PayoutRequestModelUm = "percent" | "actual" | "percentneg";

export const PayoutRequestModelUm = {
    Percent: "percent",
    Actual: "actual",
    Percentneg: "percentneg",
} as const;
