/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of Transaction.
 *
 * <details> <summary>Valid Values</summary>
 *
 * - `1` - **Credit Card Only: Sale Transaction.** Processes a sale and charges the customer.
 *
 * - `2` - **Credit Card Only: Auth Transaction.** Authorizes and holds the requested total on the credit card.
 *
 * - `3` - **Credit Card Only: Capture Transaction.** Finalizes a prior Auth Transaction and charges the customer.
 *
 * - `4` - **Credit Card Only: Reverse Authorization.** Reverses a prior Auth or Sale Transaction and releases the credit hold.
 *
 * - `5` - **Credit Card Only: Refund Transaction.** Refunds a prior Capture or Sale Transaction (total may be specified for a partial refund).
 *
 * - `7` - **Echeck Only: Echeck Sale Transaction.** Sale Transaction for ECheck payment.
 *
 * - `8` - **Echeck Only: Echeck Refund Transaction.** Refund Transaction for prior ECheck Sale Transaction.
 *
 * - `11` - **Echeck Only: Echeck Redeposit Transaction.** Attempt to redeposit a prior failed eCheck Sale Transaction.
 *
 * - `12` - **Echeck Only: Echeck Account Verification Transaction.** Attempt to verify eCheck payment details.
 *
 *  </details>
 */
export type TxnsModelType = "1" | "2" | "3" | "4" | "5" | "7" | "8" | "11" | "12";

export const TxnsModelType = {
    One: "1",
    Two: "2",
    Three: "3",
    Four: "4",
    Five: "5",
    Seven: "7",
    Eight: "8",
    Eleven: "11",
    Twelve: "12",
} as const;
