/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetFilesResponseResponseDetailsPage } from "./GetFilesResponseResponseDetailsPage";

export const GetFilesResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetFilesResponseResponseDetails.Raw,
    ButtonclikrApi.GetFilesResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetFilesResponseResponseDetailsPage.optional(),
});

export declare namespace GetFilesResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetFilesResponseResponseDetailsPage.Raw | null;
    }
}
