/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostMembersRequestFrozen: core.serialization.Schema<
    serializers.PostMembersRequestFrozen.Raw,
    ButtonclikrApi.PostMembersRequestFrozen
> = core.serialization.enum_(["0", "1"]);

export declare namespace PostMembersRequestFrozen {
    type Raw = "0" | "1";
}
