/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostMembersRequestSignificantResponsibility: core.serialization.Schema<
    serializers.PostMembersRequestSignificantResponsibility.Raw,
    ButtonclikrApi.PostMembersRequestSignificantResponsibility
> = core.serialization.enum_(["0", "1"]);

export declare namespace PostMembersRequestSignificantResponsibility {
    type Raw = "0" | "1";
}
