/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteTeamLoginsIdResponseResponseDetailsPage } from "./DeleteTeamLoginsIdResponseResponseDetailsPage";

export const DeleteTeamLoginsIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.DeleteTeamLoginsIdResponseResponseDetails.Raw,
    ButtonclikrApi.DeleteTeamLoginsIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: DeleteTeamLoginsIdResponseResponseDetailsPage.optional(),
});

export declare namespace DeleteTeamLoginsIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: DeleteTeamLoginsIdResponseResponseDetailsPage.Raw | null;
    }
}
