/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteTeamsIdResponseResponse } from "./DeleteTeamsIdResponseResponse";
import { DeleteTeamsIdResponseDetails } from "./DeleteTeamsIdResponseDetails";

export const DeleteTeamsIdResponse: core.serialization.ObjectSchema<
    serializers.DeleteTeamsIdResponse.Raw,
    ButtonclikrApi.DeleteTeamsIdResponse
> = core.serialization.object({
    response: DeleteTeamsIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: DeleteTeamsIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace DeleteTeamsIdResponse {
    interface Raw {
        response?: DeleteTeamsIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: DeleteTeamsIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
