/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetTeamLoginsIdResponseDetailsPage } from "./GetTeamLoginsIdResponseDetailsPage";

export const GetTeamLoginsIdResponseDetails: core.serialization.ObjectSchema<
    serializers.GetTeamLoginsIdResponseDetails.Raw,
    ButtonclikrApi.GetTeamLoginsIdResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetTeamLoginsIdResponseDetailsPage.optional(),
});

export declare namespace GetTeamLoginsIdResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetTeamLoginsIdResponseDetailsPage.Raw | null;
    }
}
