/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetTeamLoginsIdResponseResponse } from "./GetTeamLoginsIdResponseResponse";
import { GetTeamLoginsIdResponseDetails } from "./GetTeamLoginsIdResponseDetails";

export const GetTeamLoginsIdResponse: core.serialization.ObjectSchema<
    serializers.GetTeamLoginsIdResponse.Raw,
    ButtonclikrApi.GetTeamLoginsIdResponse
> = core.serialization.object({
    response: GetTeamLoginsIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: GetTeamLoginsIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetTeamLoginsIdResponse {
    interface Raw {
        response?: GetTeamLoginsIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: GetTeamLoginsIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
