/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetTeamLoginsIdResponseResponseDetailsPage } from "./GetTeamLoginsIdResponseResponseDetailsPage";

export const GetTeamLoginsIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetTeamLoginsIdResponseResponseDetails.Raw,
    ButtonclikrApi.GetTeamLoginsIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetTeamLoginsIdResponseResponseDetailsPage.optional(),
});

export declare namespace GetTeamLoginsIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetTeamLoginsIdResponseResponseDetailsPage.Raw | null;
    }
}
