/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostTeamLoginsRequestDelete: core.serialization.Schema<
    serializers.PostTeamLoginsRequestDelete.Raw,
    ButtonclikrApi.PostTeamLoginsRequestDelete
> = core.serialization.enum_(["0", "1"]);

export declare namespace PostTeamLoginsRequestDelete {
    type Raw = "0" | "1";
}
