/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutTeamLoginsIdRequestRead: core.serialization.Schema<
    serializers.PutTeamLoginsIdRequestRead.Raw,
    ButtonclikrApi.PutTeamLoginsIdRequestRead
> = core.serialization.enum_(["0", "1"]);

export declare namespace PutTeamLoginsIdRequestRead {
    type Raw = "0" | "1";
}
