/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteDisbursementEntitiesLogIdResponseResponseDetails } from "./DeleteDisbursementEntitiesLogIdResponseResponseDetails";

export const DeleteDisbursementEntitiesLogIdResponseResponse: core.serialization.ObjectSchema<
    serializers.DeleteDisbursementEntitiesLogIdResponseResponse.Raw,
    ButtonclikrApi.DeleteDisbursementEntitiesLogIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: DeleteDisbursementEntitiesLogIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace DeleteDisbursementEntitiesLogIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: DeleteDisbursementEntitiesLogIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
