/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostDisbursementEntitiesLogResponseResponse } from "./PostDisbursementEntitiesLogResponseResponse";

export const PostDisbursementEntitiesLogResponse: core.serialization.ObjectSchema<
    serializers.PostDisbursementEntitiesLogResponse.Raw,
    ButtonclikrApi.PostDisbursementEntitiesLogResponse
> = core.serialization.object({
    response: PostDisbursementEntitiesLogResponseResponse.optional(),
});

export declare namespace PostDisbursementEntitiesLogResponse {
    interface Raw {
        response?: PostDisbursementEntitiesLogResponseResponse.Raw | null;
    }
}
