/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutDisbursementEntitiesLogIdResponseResponseDetails } from "./PutDisbursementEntitiesLogIdResponseResponseDetails";

export const PutDisbursementEntitiesLogIdResponseResponse: core.serialization.ObjectSchema<
    serializers.PutDisbursementEntitiesLogIdResponseResponse.Raw,
    ButtonclikrApi.PutDisbursementEntitiesLogIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: PutDisbursementEntitiesLogIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PutDisbursementEntitiesLogIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: PutDisbursementEntitiesLogIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
