/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetReportResultsResponseResponseDetailsPage } from "./GetReportResultsResponseResponseDetailsPage";

export const GetReportResultsResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetReportResultsResponseResponseDetails.Raw,
    ButtonclikrApi.GetReportResultsResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetReportResultsResponseResponseDetailsPage.optional(),
});

export declare namespace GetReportResultsResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetReportResultsResponseResponseDetailsPage.Raw | null;
    }
}
