/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutReportResultsIdRequestStatus: core.serialization.Schema<
    serializers.PutReportResultsIdRequestStatus.Raw,
    ButtonclikrApi.PutReportResultsIdRequestStatus
> = core.serialization.enum_(["pending", "processed"]);

export declare namespace PutReportResultsIdRequestStatus {
    type Raw = "pending" | "processed";
}
