/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ButtonclikrApi from "../../../index";

export interface GetNotesResponse {
    response?: ButtonclikrApi.GetNotesResponseResponse;
    data?: unknown;
    /** An object describing the response, including the request ID and pagination indicators. */
    details?: ButtonclikrApi.GetNotesResponseDetails;
    errors?: unknown;
}
