/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The current status of the document upload.
 *
 * <details>
 * <summary>Valid Values</summary>
 *
 * - `created` - The database record has been created.
 *
 * - `processed` - The document upload for this record was processed successfully.
 *
 * - `failed` - The document upload for this record could not be processed
 *
 * </details>
 */
export type PostNoteDocumentsRequestStatus = "created" | "processed" | "failed";

export const PostNoteDocumentsRequestStatus = {
    Created: "created",
    Processed: "processed",
    Failed: "failed",
} as const;
