/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteAggregationsIdResponseResponseDetailsPage } from "./DeleteAggregationsIdResponseResponseDetailsPage";

export const DeleteAggregationsIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.DeleteAggregationsIdResponseResponseDetails.Raw,
    ButtonclikrApi.DeleteAggregationsIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: DeleteAggregationsIdResponseResponseDetailsPage.optional(),
});

export declare namespace DeleteAggregationsIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: DeleteAggregationsIdResponseResponseDetailsPage.Raw | null;
    }
}
