/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetAggregationResultsIdResponseResponse } from "./GetAggregationResultsIdResponseResponse";
import { GetAggregationResultsIdResponseDetails } from "./GetAggregationResultsIdResponseDetails";

export const GetAggregationResultsIdResponse: core.serialization.ObjectSchema<
    serializers.GetAggregationResultsIdResponse.Raw,
    ButtonclikrApi.GetAggregationResultsIdResponse
> = core.serialization.object({
    response: GetAggregationResultsIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: GetAggregationResultsIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetAggregationResultsIdResponse {
    interface Raw {
        response?: GetAggregationResultsIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: GetAggregationResultsIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
