/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetAggregationResultGroupsIdResponseDetailsPage } from "./GetAggregationResultGroupsIdResponseDetailsPage";

export const GetAggregationResultGroupsIdResponseDetails: core.serialization.ObjectSchema<
    serializers.GetAggregationResultGroupsIdResponseDetails.Raw,
    ButtonclikrApi.GetAggregationResultGroupsIdResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetAggregationResultGroupsIdResponseDetailsPage.optional(),
});

export declare namespace GetAggregationResultGroupsIdResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetAggregationResultGroupsIdResponseDetailsPage.Raw | null;
    }
}
