/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetAggregationsIdResponseResponse } from "./GetAggregationsIdResponseResponse";
import { GetAggregationsIdResponseDetails } from "./GetAggregationsIdResponseDetails";

export const GetAggregationsIdResponse: core.serialization.ObjectSchema<
    serializers.GetAggregationsIdResponse.Raw,
    ButtonclikrApi.GetAggregationsIdResponse
> = core.serialization.object({
    response: GetAggregationsIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: GetAggregationsIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetAggregationsIdResponse {
    interface Raw {
        response?: GetAggregationsIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: GetAggregationsIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
