/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutAggregationsIdRequestInactive: core.serialization.Schema<
    serializers.PutAggregationsIdRequestInactive.Raw,
    ButtonclikrApi.PutAggregationsIdRequestInactive
> = core.serialization.enum_(["0", "1"]);

export declare namespace PutAggregationsIdRequestInactive {
    type Raw = "0" | "1";
}
