/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetAuditLogsResponseResponse } from "./GetAuditLogsResponseResponse";

export const GetAuditLogsResponse: core.serialization.ObjectSchema<
    serializers.GetAuditLogsResponse.Raw,
    ButtonclikrApi.GetAuditLogsResponse
> = core.serialization.object({
    response: GetAuditLogsResponseResponse.optional(),
});

export declare namespace GetAuditLogsResponse {
    interface Raw {
        response?: GetAuditLogsResponseResponse.Raw | null;
    }
}
