/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether this resource is marked as inactive or not, whether it's marked as active or inactive.
 */
export type PutSecretsIdRequestInactive = "0" | "1";

export const PutSecretsIdRequestInactive = {
    Zero: "0",
    One: "1",
} as const;
