/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of secret. Valid Values: baseKey, sftp, publicKey, privateKey, ecPrivateKey, apikey, oldPrivateKey.
 */
export type PutSecretsIdRequestType =
    | "baseKey"
    | "sftp"
    | "publicKey"
    | "privateKey"
    | "ecPrivateKey"
    | "apikey"
    | "oldPrivateKey";

export const PutSecretsIdRequestType = {
    BaseKey: "baseKey",
    Sftp: "sftp",
    PublicKey: "publicKey",
    PrivateKey: "privateKey",
    EcPrivateKey: "ecPrivateKey",
    Apikey: "apikey",
    OldPrivateKey: "oldPrivateKey",
} as const;
