/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether or not this user should have multi factor authentication (MFA) feature.
 */
export type PostLoginsRequestMfaEnabled = "0" | "1";

export const PostLoginsRequestMfaEnabled = {
    Zero: "0",
    One: "1",
} as const;
