/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of this invoiceResult
 *
 * <details>
 * <summary>Valid Values</summary>
 *
 * - `success` - **Successfuly processed.**
 *
 * - `failure` - **Failed to process.**
 *
 * </details>
 */
export type PostInvoiceResultsRequestStatus = "success" | "failure";

export const PostInvoiceResultsRequestStatus = {
    Success: "success",
    Failure: "failure",
} as const;
