/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of invoice is the type of invoice.
 *
 * <details>
 * <summary>Valid Values</summary>
 *
 * - `single` - **A single-use invoice**
 * - `multiUse` - **A static, reusable invoice. (Payment Page.)**
 * - `recurring` - **A subscription-based invoice.**
 *
 * </details>
 */
export type PutInvoicesIdRequestType = "single" | "multiUse" | "recurring";

export const PutInvoicesIdRequestType = {
    Single: "single",
    MultiUse: "multiUse",
    Recurring: "recurring",
} as const;
