/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetTerminalTxnDatasIdResponseResponseDetailsPage } from "./GetTerminalTxnDatasIdResponseResponseDetailsPage";

export const GetTerminalTxnDatasIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetTerminalTxnDatasIdResponseResponseDetails.Raw,
    ButtonclikrApi.GetTerminalTxnDatasIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetTerminalTxnDatasIdResponseResponseDetailsPage.optional(),
});

export declare namespace GetTerminalTxnDatasIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetTerminalTxnDatasIdResponseResponseDetailsPage.Raw | null;
    }
}
