/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostTerminalTxnDatasResponseResponseDetails } from "./PostTerminalTxnDatasResponseResponseDetails";

export const PostTerminalTxnDatasResponseResponse: core.serialization.ObjectSchema<
    serializers.PostTerminalTxnDatasResponseResponse.Raw,
    ButtonclikrApi.PostTerminalTxnDatasResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: PostTerminalTxnDatasResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PostTerminalTxnDatasResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: PostTerminalTxnDatasResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
