/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostTerminalTxnDatasResponseResponse } from "./PostTerminalTxnDatasResponseResponse";

export const PostTerminalTxnDatasResponse: core.serialization.ObjectSchema<
    serializers.PostTerminalTxnDatasResponse.Raw,
    ButtonclikrApi.PostTerminalTxnDatasResponse
> = core.serialization.object({
    response: PostTerminalTxnDatasResponseResponse.optional(),
});

export declare namespace PostTerminalTxnDatasResponse {
    interface Raw {
        response?: PostTerminalTxnDatasResponseResponse.Raw | null;
    }
}
