/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostTerminalTxnMetadatasResponseResponseDetailsPage } from "./PostTerminalTxnMetadatasResponseResponseDetailsPage";

export const PostTerminalTxnMetadatasResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.PostTerminalTxnMetadatasResponseResponseDetails.Raw,
    ButtonclikrApi.PostTerminalTxnMetadatasResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: PostTerminalTxnMetadatasResponseResponseDetailsPage.optional(),
});

export declare namespace PostTerminalTxnMetadatasResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: PostTerminalTxnMetadatasResponseResponseDetailsPage.Raw | null;
    }
}
