/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ButtonclikrApi from "../../../index";

export interface DeleteAccountRefsIdResponseResponse {
    data?: unknown;
    details?: ButtonclikrApi.Details;
    errors?: ButtonclikrApi.Error_;
}
