/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteContactsIdResponseResponse } from "./DeleteContactsIdResponseResponse";
import { DeleteContactsIdResponseDetails } from "./DeleteContactsIdResponseDetails";

export const DeleteContactsIdResponse: core.serialization.ObjectSchema<
    serializers.DeleteContactsIdResponse.Raw,
    ButtonclikrApi.DeleteContactsIdResponse
> = core.serialization.object({
    response: DeleteContactsIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: DeleteContactsIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace DeleteContactsIdResponse {
    interface Raw {
        response?: DeleteContactsIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: DeleteContactsIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
