/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetContactsIdResponseDetailsPage } from "./GetContactsIdResponseDetailsPage";

export const GetContactsIdResponseDetails: core.serialization.ObjectSchema<
    serializers.GetContactsIdResponseDetails.Raw,
    ButtonclikrApi.GetContactsIdResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetContactsIdResponseDetailsPage.optional(),
});

export declare namespace GetContactsIdResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetContactsIdResponseDetailsPage.Raw | null;
    }
}
