/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetDivisionsResponseResponseDetailsPage } from "./GetDivisionsResponseResponseDetailsPage";

export const GetDivisionsResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetDivisionsResponseResponseDetails.Raw,
    ButtonclikrApi.GetDivisionsResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetDivisionsResponseResponseDetailsPage.optional(),
});

export declare namespace GetDivisionsResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetDivisionsResponseResponseDetailsPage.Raw | null;
    }
}
