/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostEntityRefsResponseResponse } from "./PostEntityRefsResponseResponse";
import { PostEntityRefsResponseDetails } from "./PostEntityRefsResponseDetails";

export const PostEntityRefsResponse: core.serialization.ObjectSchema<
    serializers.PostEntityRefsResponse.Raw,
    ButtonclikrApi.PostEntityRefsResponse
> = core.serialization.object({
    response: PostEntityRefsResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: PostEntityRefsResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PostEntityRefsResponse {
    interface Raw {
        response?: PostEntityRefsResponseResponse.Raw | null;
        data?: unknown | null;
        details?: PostEntityRefsResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
