/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteBillingEventsIdResponseResponseDetails } from "./DeleteBillingEventsIdResponseResponseDetails";

export const DeleteBillingEventsIdResponseResponse: core.serialization.ObjectSchema<
    serializers.DeleteBillingEventsIdResponseResponse.Raw,
    ButtonclikrApi.DeleteBillingEventsIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: DeleteBillingEventsIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace DeleteBillingEventsIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: DeleteBillingEventsIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
