/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetBillingsResponseDetailsPage } from "./GetBillingsResponseDetailsPage";

export const GetBillingsResponseDetails: core.serialization.ObjectSchema<
    serializers.GetBillingsResponseDetails.Raw,
    ButtonclikrApi.GetBillingsResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetBillingsResponseDetailsPage.optional(),
});

export declare namespace GetBillingsResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetBillingsResponseDetailsPage.Raw | null;
    }
}
