/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetBillingModifiersIdResponseResponse } from "./GetBillingModifiersIdResponseResponse";
import { GetBillingModifiersIdResponseDetails } from "./GetBillingModifiersIdResponseDetails";

export const GetBillingModifiersIdResponse: core.serialization.ObjectSchema<
    serializers.GetBillingModifiersIdResponse.Raw,
    ButtonclikrApi.GetBillingModifiersIdResponse
> = core.serialization.object({
    response: GetBillingModifiersIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: GetBillingModifiersIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetBillingModifiersIdResponse {
    interface Raw {
        response?: GetBillingModifiersIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: GetBillingModifiersIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
