/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostBillingEventsResponseResponse } from "./PostBillingEventsResponseResponse";
import { PostBillingEventsResponseDetails } from "./PostBillingEventsResponseDetails";

export const PostBillingEventsResponse: core.serialization.ObjectSchema<
    serializers.PostBillingEventsResponse.Raw,
    ButtonclikrApi.PostBillingEventsResponse
> = core.serialization.object({
    response: PostBillingEventsResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: PostBillingEventsResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PostBillingEventsResponse {
    interface Raw {
        response?: PostBillingEventsResponseResponse.Raw | null;
        data?: unknown | null;
        details?: PostBillingEventsResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
