/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostDecisionsRequestTarget: core.serialization.Schema<
    serializers.PostDecisionsRequestTarget.Raw,
    ButtonclikrApi.PostDecisionsRequestTarget
> = core.serialization.enum_([
    "activation",
    "auth",
    "postauth",
    "capture",
    "refund",
    "createEntity",
    "underwriting",
    "preboard",
    "postboard",
    "txn",
    "txnVolume",
    "payout",
    "payoutVolume",
]);

export declare namespace PostDecisionsRequestTarget {
    type Raw =
        | "activation"
        | "auth"
        | "postauth"
        | "capture"
        | "refund"
        | "createEntity"
        | "underwriting"
        | "preboard"
        | "postboard"
        | "txn"
        | "txnVolume"
        | "payout"
        | "payoutVolume";
}
