/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutDecisionsIdResponseResponseDetailsPage } from "./PutDecisionsIdResponseResponseDetailsPage";

export const PutDecisionsIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.PutDecisionsIdResponseResponseDetails.Raw,
    ButtonclikrApi.PutDecisionsIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: PutDecisionsIdResponseResponseDetailsPage.optional(),
});

export declare namespace PutDecisionsIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: PutDecisionsIdResponseResponseDetailsPage.Raw | null;
    }
}
