/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutDecisionsIdResponseResponseDetails } from "./PutDecisionsIdResponseResponseDetails";

export const PutDecisionsIdResponseResponse: core.serialization.ObjectSchema<
    serializers.PutDecisionsIdResponseResponse.Raw,
    ButtonclikrApi.PutDecisionsIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: PutDecisionsIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PutDecisionsIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: PutDecisionsIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
