/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ButtonclikrApi from "../../../index";

export interface DeleteEntityRoutesIdResponse {
    response?: ButtonclikrApi.DeleteEntityRoutesIdResponseResponse;
}
