/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ButtonclikrApi from "../../api/index";
import * as core from "../../core";
import { BookingPaymentCurrency } from "./BookingPaymentCurrency";
import { BookingPaymentSource } from "./BookingPaymentSource";
import { BookingPaymentStatus } from "./BookingPaymentStatus";

export const BookingPayment: core.serialization.ObjectSchema<
    serializers.BookingPayment.Raw,
    ButtonclikrApi.BookingPayment
> = core.serialization.object({
    id: core.serialization.string().optional(),
    amount: core.serialization.number().optional(),
    currency: BookingPaymentCurrency.optional(),
    source: BookingPaymentSource.optional(),
    status: BookingPaymentStatus.optional(),
});

export declare namespace BookingPayment {
    interface Raw {
        id?: string | null;
        amount?: number | null;
        currency?: BookingPaymentCurrency.Raw | null;
        source?: BookingPaymentSource.Raw | null;
        status?: BookingPaymentStatus.Raw | null;
    }
}
