/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ButtonclikrApi from "../../api/index";
import * as core from "../../core";

export const ChangeRequestModelOperation: core.serialization.Schema<
    serializers.ChangeRequestModelOperation.Raw,
    ButtonclikrApi.ChangeRequestModelOperation
> = core.serialization.enum_(["create", "update"]);

export declare namespace ChangeRequestModelOperation {
    type Raw = "create" | "update";
}
