/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ButtonclikrApi from "../../api/index";
import * as core from "../../core";

export const TerminalTxnsMetadatasModelType: core.serialization.Schema<
    serializers.TerminalTxnsMetadatasModelType.Raw,
    ButtonclikrApi.TerminalTxnsMetadatasModelType
> = core.serialization.enum_(["amounts", "emv", "network", "timeout", "firstTxn", "discretionary"]);

export declare namespace TerminalTxnsMetadatasModelType {
    type Raw = "amounts" | "emv" | "network" | "timeout" | "firstTxn" | "discretionary";
}
