/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ButtonclikrApi from "../../api/index";
import * as core from "../../core";
import { Id } from "./Id";
import { Created } from "./Created";
import { Modified } from "./Modified";
import { Creator } from "./Creator";
import { Modifier } from "./Modifier";

export const TerminalTxnsDatasModel: core.serialization.ObjectSchema<
    serializers.TerminalTxnsDatasModel.Raw,
    ButtonclikrApi.TerminalTxnsDatasModel
> = core.serialization.object({
    id: Id.optional(),
    created: Created.optional(),
    modified: Modified.optional(),
    creator: Creator.optional(),
    modifier: Modifier.optional(),
    terminalTxn: core.serialization.string().optional(),
    signature: core.serialization.number().optional(),
});

export declare namespace TerminalTxnsDatasModel {
    interface Raw {
        id?: Id.Raw | null;
        created?: Created.Raw | null;
        modified?: Modified.Raw | null;
        creator?: Creator.Raw | null;
        modifier?: Modifier.Raw | null;
        terminalTxn?: string | null;
        signature?: number | null;
    }
}
