/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ButtonclikrApi from "../../api/index";
import * as core from "../../core";

export const TxnsModelCvvStatus: core.serialization.Schema<
    serializers.TxnsModelCvvStatus.Raw,
    ButtonclikrApi.TxnsModelCvvStatus
> = core.serialization.enum_(["notPresent", "illegible", "notProvided"]);

export declare namespace TxnsModelCvvStatus {
    type Raw = "notPresent" | "illegible" | "notProvided";
}
