/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ButtonclikrApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { PostAssessmentsRequestEvent } from "../../types/PostAssessmentsRequestEvent";
import { PostAssessmentsRequestPlatform } from "../../types/PostAssessmentsRequestPlatform";
import { PostAssessmentsRequestCurrency } from "../../types/PostAssessmentsRequestCurrency";

export const PostAssessmentsRequest: core.serialization.Schema<
    serializers.PostAssessmentsRequest.Raw,
    ButtonclikrApi.PostAssessmentsRequest
> = core.serialization.object({
    entity: core.serialization.unknown(),
    onentity: core.serialization.unknown().optional(),
    forentity: core.serialization.unknown().optional(),
    partition: core.serialization.unknown().optional(),
    fee: core.serialization.unknown().optional(),
    disbursement: core.serialization.unknown().optional(),
    txn: core.serialization.unknown().optional(),
    chargeback: core.serialization.unknown().optional(),
    merchant: core.serialization.unknown().optional(),
    event: PostAssessmentsRequestEvent.optional(),
    eventId: core.serialization.unknown().optional(),
    description: core.serialization.unknown().optional(),
    amount: core.serialization.unknown(),
    platform: PostAssessmentsRequestPlatform.optional(),
    currency: PostAssessmentsRequestCurrency,
});

export declare namespace PostAssessmentsRequest {
    interface Raw {
        entity?: unknown;
        onentity?: unknown | null;
        forentity?: unknown | null;
        partition?: unknown | null;
        fee?: unknown | null;
        disbursement?: unknown | null;
        txn?: unknown | null;
        chargeback?: unknown | null;
        merchant?: unknown | null;
        event?: PostAssessmentsRequestEvent.Raw | null;
        eventId?: unknown | null;
        description?: unknown | null;
        amount?: unknown;
        platform?: PostAssessmentsRequestPlatform.Raw | null;
        currency: PostAssessmentsRequestCurrency.Raw;
    }
}
