/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteLoginsIdResponseResponse } from "./DeleteLoginsIdResponseResponse";
import { DeleteLoginsIdResponseDetails } from "./DeleteLoginsIdResponseDetails";

export const DeleteLoginsIdResponse: core.serialization.ObjectSchema<
    serializers.DeleteLoginsIdResponse.Raw,
    ButtonclikrApi.DeleteLoginsIdResponse
> = core.serialization.object({
    response: DeleteLoginsIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: DeleteLoginsIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace DeleteLoginsIdResponse {
    interface Raw {
        response?: DeleteLoginsIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: DeleteLoginsIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
