/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetLoginsHelpersResponseResponseDetailsPage } from "./GetLoginsHelpersResponseResponseDetailsPage";

export const GetLoginsHelpersResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetLoginsHelpersResponseResponseDetails.Raw,
    ButtonclikrApi.GetLoginsHelpersResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetLoginsHelpersResponseResponseDetailsPage.optional(),
});

export declare namespace GetLoginsHelpersResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetLoginsHelpersResponseResponseDetailsPage.Raw | null;
    }
}
