/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostLoginsResponseResponse } from "./PostLoginsResponseResponse";
import { PostLoginsResponseDetails } from "./PostLoginsResponseDetails";

export const PostLoginsResponse: core.serialization.ObjectSchema<
    serializers.PostLoginsResponse.Raw,
    ButtonclikrApi.PostLoginsResponse
> = core.serialization.object({
    response: PostLoginsResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: PostLoginsResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PostLoginsResponse {
    interface Raw {
        response?: PostLoginsResponseResponse.Raw | null;
        data?: unknown | null;
        details?: PostLoginsResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
