/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutLoginsIdResponseResponse } from "./PutLoginsIdResponseResponse";
import { PutLoginsIdResponseDetails } from "./PutLoginsIdResponseDetails";

export const PutLoginsIdResponse: core.serialization.ObjectSchema<
    serializers.PutLoginsIdResponse.Raw,
    ButtonclikrApi.PutLoginsIdResponse
> = core.serialization.object({
    response: PutLoginsIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: PutLoginsIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PutLoginsIdResponse {
    interface Raw {
        response?: PutLoginsIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: PutLoginsIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
