/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ButtonclikrApi from "../../../../index";

/**
 * @example
 *     {}
 */
export interface PostPaymentUpdatesRequest {
    paymentUpdateGroup?: unknown;
    /** The payment associated with this PaymentUpdate. */
    payment?: ButtonclikrApi.PostPaymentUpdatesRequestPayment;
    /** The status of the paymentUpdate. */
    status?: ButtonclikrApi.PostPaymentUpdatesRequestStatus;
    token?: unknown;
    account?: unknown;
    /** The platform used to process this PaymentUpdate. */
    platform?: ButtonclikrApi.PostPaymentUpdatesRequestPlatform;
    ref?: unknown;
    clientRef?: unknown;
    message?: unknown;
    expiration?: unknown;
}
