/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether this resource is marked as frozen. Valid Values: `0` - Not Frozen, `1` - Frozen.
 */
export type PostReservesRequestFrozen = "0" | "1";

export const PostReservesRequestFrozen = {
    Zero: "0",
    One: "1",
} as const;
