/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether this resource is marked as frozen or not frozen.
 */
export type PutReservesIdRequestFrozen = "0" | "1";

export const PutReservesIdRequestFrozen = {
    Zero: "0",
    One: "1",
} as const;
