/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether this resource is marked as inactive or not.
 */
export type PutReservesIdRequestInactive = "0" | "1";

export const PutReservesIdRequestInactive = {
    Zero: "0",
    One: "1",
} as const;
