/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteFeesIdResponseResponse } from "./DeleteFeesIdResponseResponse";
import { DeleteFeesIdResponseDetails } from "./DeleteFeesIdResponseDetails";

export const DeleteFeesIdResponse: core.serialization.ObjectSchema<
    serializers.DeleteFeesIdResponse.Raw,
    ButtonclikrApi.DeleteFeesIdResponse
> = core.serialization.object({
    response: DeleteFeesIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: DeleteFeesIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace DeleteFeesIdResponse {
    interface Raw {
        response?: DeleteFeesIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: DeleteFeesIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
