/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetAssessmentsResponseResponse } from "./GetAssessmentsResponseResponse";
import { GetAssessmentsResponseDetails } from "./GetAssessmentsResponseDetails";

export const GetAssessmentsResponse: core.serialization.ObjectSchema<
    serializers.GetAssessmentsResponse.Raw,
    ButtonclikrApi.GetAssessmentsResponse
> = core.serialization.object({
    response: GetAssessmentsResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: GetAssessmentsResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetAssessmentsResponse {
    interface Raw {
        response?: GetAssessmentsResponseResponse.Raw | null;
        data?: unknown | null;
        details?: GetAssessmentsResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
