/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostFeesRequestUm: core.serialization.Schema<
    serializers.PostFeesRequestUm.Raw,
    ButtonclikrApi.PostFeesRequestUm
> = core.serialization.enum_(["1", "2", "3"]);

export declare namespace PostFeesRequestUm {
    type Raw = "1" | "2" | "3";
}
