/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostFeesResponseResponseDetailsPage } from "./PostFeesResponseResponseDetailsPage";

export const PostFeesResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.PostFeesResponseResponseDetails.Raw,
    ButtonclikrApi.PostFeesResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: PostFeesResponseResponseDetailsPage.optional(),
});

export declare namespace PostFeesResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: PostFeesResponseResponseDetailsPage.Raw | null;
    }
}
