/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutFeesIdRequestFrozen: core.serialization.Schema<
    serializers.PutFeesIdRequestFrozen.Raw,
    ButtonclikrApi.PutFeesIdRequestFrozen
> = core.serialization.enum_(["0", "1"]);

export declare namespace PutFeesIdRequestFrozen {
    type Raw = "0" | "1";
}
