/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutFeeRulesIdResponseResponse } from "./PutFeeRulesIdResponseResponse";
import { PutFeeRulesIdResponseDetails } from "./PutFeeRulesIdResponseDetails";

export const PutFeeRulesIdResponse: core.serialization.ObjectSchema<
    serializers.PutFeeRulesIdResponse.Raw,
    ButtonclikrApi.PutFeeRulesIdResponse
> = core.serialization.object({
    response: PutFeeRulesIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: PutFeeRulesIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PutFeeRulesIdResponse {
    interface Raw {
        response?: PutFeeRulesIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: PutFeeRulesIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
