/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteOrgFlowsIdResponseResponseDetailsPage } from "./DeleteOrgFlowsIdResponseResponseDetailsPage";

export const DeleteOrgFlowsIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.DeleteOrgFlowsIdResponseResponseDetails.Raw,
    ButtonclikrApi.DeleteOrgFlowsIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: DeleteOrgFlowsIdResponseResponseDetailsPage.optional(),
});

export declare namespace DeleteOrgFlowsIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: DeleteOrgFlowsIdResponseResponseDetailsPage.Raw | null;
    }
}
