/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteOrgFlowActionsIdResponseDetailsPage } from "./DeleteOrgFlowActionsIdResponseDetailsPage";

export const DeleteOrgFlowActionsIdResponseDetails: core.serialization.ObjectSchema<
    serializers.DeleteOrgFlowActionsIdResponseDetails.Raw,
    ButtonclikrApi.DeleteOrgFlowActionsIdResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: DeleteOrgFlowActionsIdResponseDetailsPage.optional(),
});

export declare namespace DeleteOrgFlowActionsIdResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: DeleteOrgFlowActionsIdResponseDetailsPage.Raw | null;
    }
}
