/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetOrgsResponseResponseDetails } from "./GetOrgsResponseResponseDetails";

export const GetOrgsResponseResponse: core.serialization.ObjectSchema<
    serializers.GetOrgsResponseResponse.Raw,
    ButtonclikrApi.GetOrgsResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: GetOrgsResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetOrgsResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: GetOrgsResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
