/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostOrgEntitiesResponseResponseDetailsPage } from "./PostOrgEntitiesResponseResponseDetailsPage";

export const PostOrgEntitiesResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.PostOrgEntitiesResponseResponseDetails.Raw,
    ButtonclikrApi.PostOrgEntitiesResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: PostOrgEntitiesResponseResponseDetailsPage.optional(),
});

export declare namespace PostOrgEntitiesResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: PostOrgEntitiesResponseResponseDetailsPage.Raw | null;
    }
}
