/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostOrgFlowsResponseResponseDetails } from "./PostOrgFlowsResponseResponseDetails";

export const PostOrgFlowsResponseResponse: core.serialization.ObjectSchema<
    serializers.PostOrgFlowsResponseResponse.Raw,
    ButtonclikrApi.PostOrgFlowsResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: PostOrgFlowsResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PostOrgFlowsResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: PostOrgFlowsResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
