/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutOrgFlowActionsIdResponseResponseDetailsPage } from "./PutOrgFlowActionsIdResponseResponseDetailsPage";

export const PutOrgFlowActionsIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.PutOrgFlowActionsIdResponseResponseDetails.Raw,
    ButtonclikrApi.PutOrgFlowActionsIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: PutOrgFlowActionsIdResponseResponseDetailsPage.optional(),
});

export declare namespace PutOrgFlowActionsIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: PutOrgFlowActionsIdResponseResponseDetailsPage.Raw | null;
    }
}
