/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ButtonclikrApi from "../../../../index";

/**
 * @example
 *     {
 *         login: {
 *             "key": "value"
 *         },
 *         entity: {
 *             "key": "value"
 *         },
 *         division: {
 *             "key": "value"
 *         },
 *         org: {
 *             "key": "value"
 *         },
 *         partition: {
 *             "key": "value"
 *         },
 *         integration: ButtonclikrApi.PutConfigurationsIdRequestIntegration.Ach,
 *         name: ButtonclikrApi.PutConfigurationsIdRequestName.Account,
 *         type: ButtonclikrApi.PutConfigurationsIdRequestType.Create,
 *         options: {
 *             "key": "value"
 *         },
 *         inactive: ButtonclikrApi.PutConfigurationsIdRequestInactive.Zero,
 *         frozen: ButtonclikrApi.PutConfigurationsIdRequestFrozen.Zero
 *     }
 */
export interface PutConfigurationsIdRequest {
    login?: unknown;
    entity?: unknown;
    division?: unknown;
    org?: unknown;
    partition?: unknown;
    /** The integration associated with this configuration resource. */
    integration: ButtonclikrApi.PutConfigurationsIdRequestIntegration;
    /** The name of this configuration resource. */
    name: ButtonclikrApi.PutConfigurationsIdRequestName;
    /** The type of configuration resource. */
    type: ButtonclikrApi.PutConfigurationsIdRequestType;
    options?: unknown;
    /** Whether this resource is marked as inactive. */
    inactive: ButtonclikrApi.PutConfigurationsIdRequestInactive;
    /** Whether this resource is marked as frozen. */
    frozen: ButtonclikrApi.PutConfigurationsIdRequestFrozen;
}
