/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ButtonclikrApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { PutInvoiceParametersIdRequestLocked } from "../../types/PutInvoiceParametersIdRequestLocked";
import { PutInvoiceParametersIdRequestType } from "../../types/PutInvoiceParametersIdRequestType";
import { PutInvoiceParametersIdRequestValue } from "../../types/PutInvoiceParametersIdRequestValue";
import { PutInvoiceParametersIdRequestInactive } from "../../types/PutInvoiceParametersIdRequestInactive";
import { PutInvoiceParametersIdRequestFrozen } from "../../types/PutInvoiceParametersIdRequestFrozen";

export const PutInvoiceParametersIdRequest: core.serialization.Schema<
    serializers.PutInvoiceParametersIdRequest.Raw,
    ButtonclikrApi.PutInvoiceParametersIdRequest
> = core.serialization.object({
    login: core.serialization.unknown(),
    entity: core.serialization.unknown().optional(),
    division: core.serialization.unknown().optional(),
    org: core.serialization.unknown().optional(),
    partition: core.serialization.unknown().optional(),
    locked: PutInvoiceParametersIdRequestLocked,
    type: PutInvoiceParametersIdRequestType,
    value: PutInvoiceParametersIdRequestValue,
    inactive: PutInvoiceParametersIdRequestInactive,
    frozen: PutInvoiceParametersIdRequestFrozen,
});

export declare namespace PutInvoiceParametersIdRequest {
    interface Raw {
        login?: unknown;
        entity?: unknown | null;
        division?: unknown | null;
        org?: unknown | null;
        partition?: unknown | null;
        locked: PutInvoiceParametersIdRequestLocked.Raw;
        type: PutInvoiceParametersIdRequestType.Raw;
        value: PutInvoiceParametersIdRequestValue.Raw;
        inactive: PutInvoiceParametersIdRequestInactive.Raw;
        frozen: PutInvoiceParametersIdRequestFrozen.Raw;
    }
}
