/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetApikeysResponseResponseDetailsPage } from "./GetApikeysResponseResponseDetailsPage";

export const GetApikeysResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetApikeysResponseResponseDetails.Raw,
    ButtonclikrApi.GetApikeysResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetApikeysResponseResponseDetailsPage.optional(),
});

export declare namespace GetApikeysResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetApikeysResponseResponseDetailsPage.Raw | null;
    }
}
