/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteWatchlistsIdResponseResponseDetails } from "./DeleteWatchlistsIdResponseResponseDetails";

export const DeleteWatchlistsIdResponseResponse: core.serialization.ObjectSchema<
    serializers.DeleteWatchlistsIdResponseResponse.Raw,
    ButtonclikrApi.DeleteWatchlistsIdResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: DeleteWatchlistsIdResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace DeleteWatchlistsIdResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: DeleteWatchlistsIdResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
