/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetWatchlistItemsIdResponseResponseDetailsPage } from "./GetWatchlistItemsIdResponseResponseDetailsPage";

export const GetWatchlistItemsIdResponseResponseDetails: core.serialization.ObjectSchema<
    serializers.GetWatchlistItemsIdResponseResponseDetails.Raw,
    ButtonclikrApi.GetWatchlistItemsIdResponseResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetWatchlistItemsIdResponseResponseDetailsPage.optional(),
});

export declare namespace GetWatchlistItemsIdResponseResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetWatchlistItemsIdResponseResponseDetailsPage.Raw | null;
    }
}
