/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostWatchlistItemsResponseResponseDetails } from "./PostWatchlistItemsResponseResponseDetails";

export const PostWatchlistItemsResponseResponse: core.serialization.ObjectSchema<
    serializers.PostWatchlistItemsResponseResponse.Raw,
    ButtonclikrApi.PostWatchlistItemsResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: PostWatchlistItemsResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PostWatchlistItemsResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: PostWatchlistItemsResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
