/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutWatchlistsIdResponseResponse } from "./PutWatchlistsIdResponseResponse";

export const PutWatchlistsIdResponse: core.serialization.ObjectSchema<
    serializers.PutWatchlistsIdResponse.Raw,
    ButtonclikrApi.PutWatchlistsIdResponse
> = core.serialization.object({
    response: PutWatchlistsIdResponseResponse.optional(),
});

export declare namespace PutWatchlistsIdResponse {
    interface Raw {
        response?: PutWatchlistsIdResponseResponse.Raw | null;
    }
}
