/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetSettlementsIdResponseResponse } from "./GetSettlementsIdResponseResponse";

export const GetSettlementsIdResponse: core.serialization.ObjectSchema<
    serializers.GetSettlementsIdResponse.Raw,
    ButtonclikrApi.GetSettlementsIdResponse
> = core.serialization.object({
    response: GetSettlementsIdResponseResponse.optional(),
});

export declare namespace GetSettlementsIdResponse {
    interface Raw {
        response?: GetSettlementsIdResponseResponse.Raw | null;
    }
}
