/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ButtonclikrApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { AlertTriggersReqBodySchemaEvent } from "../../types/AlertTriggersReqBodySchemaEvent";
import { Inactive } from "../../../../types/Inactive";
import { Frozen } from "../../../../types/Frozen";

export const AlertTriggersReqBodySchema: core.serialization.Schema<
    serializers.AlertTriggersReqBodySchema.Raw,
    ButtonclikrApi.AlertTriggersReqBodySchema
> = core.serialization.object({
    alert: core.serialization.string(),
    event: AlertTriggersReqBodySchemaEvent,
    resource: core.serialization.number(),
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    inactive: Inactive,
    frozen: Frozen,
});

export declare namespace AlertTriggersReqBodySchema {
    interface Raw {
        alert: string;
        event: AlertTriggersReqBodySchemaEvent.Raw;
        resource: number;
        name?: string | null;
        description?: string | null;
        inactive: Inactive.Raw;
        frozen: Frozen.Raw;
    }
}
