/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostAuthTokensRequestInactive: core.serialization.Schema<
    serializers.PostAuthTokensRequestInactive.Raw,
    ButtonclikrApi.PostAuthTokensRequestInactive
> = core.serialization.enum_(["0", "1"]);

export declare namespace PostAuthTokensRequestInactive {
    type Raw = "0" | "1";
}
