/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ButtonclikrApi from "../../../../index";

/**
 * @example
 *     {
 *         entity: {
 *             "key": "value"
 *         },
 *         onentity: {
 *             "key": "value"
 *         },
 *         forentity: {
 *             "key": "value"
 *         },
 *         partition: {
 *             "key": "value"
 *         },
 *         fee: {
 *             "key": "value"
 *         },
 *         disbursement: {
 *             "key": "value"
 *         },
 *         txn: {
 *             "key": "value"
 *         },
 *         chargeback: {
 *             "key": "value"
 *         },
 *         merchant: {
 *             "key": "value"
 *         },
 *         event: ButtonclikrApi.PostAssessmentsRequestEvent.One,
 *         eventId: {
 *             "key": "value"
 *         },
 *         description: {
 *             "key": "value"
 *         },
 *         amount: {
 *             "key": "value"
 *         },
 *         platform: ButtonclikrApi.PostAssessmentsRequestPlatform.Apple,
 *         currency: ButtonclikrApi.PostAssessmentsRequestCurrency.Aed
 *     }
 */
export interface PostAssessmentsRequest {
    entity?: unknown;
    onentity?: unknown;
    forentity?: unknown;
    partition?: unknown;
    fee?: unknown;
    disbursement?: unknown;
    txn?: unknown;
    chargeback?: unknown;
    merchant?: unknown;
    /** The type of event that triggered this assessments resource. */
    event?: ButtonclikrApi.PostAssessmentsRequestEvent;
    eventId?: unknown;
    description?: unknown;
    amount?: unknown;
    platform?: ButtonclikrApi.PostAssessmentsRequestPlatform;
    /** The currency of the amount in this assessments resource. */
    currency: ButtonclikrApi.PostAssessmentsRequestCurrency;
}
