/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ButtonclikrApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { PostAggregationsRequestType } from "../../types/PostAggregationsRequestType";
import { PostAggregationsRequestLevel } from "../../types/PostAggregationsRequestLevel";
import { PostAggregationsRequestStatus } from "../../types/PostAggregationsRequestStatus";
import { PostAggregationsRequestSchedule } from "../../types/PostAggregationsRequestSchedule";
import { PostAggregationsRequestDefault } from "../../types/PostAggregationsRequestDefault";
import { PostAggregationsRequestInactive } from "../../types/PostAggregationsRequestInactive";
import { PostAggregationsRequestFrozen } from "../../types/PostAggregationsRequestFrozen";

export const PostAggregationsRequest: core.serialization.Schema<
    serializers.PostAggregationsRequest.Raw,
    ButtonclikrApi.PostAggregationsRequest
> = core.serialization.object({
    login: core.serialization.unknown(),
    entity: core.serialization.unknown().optional(),
    forlogin: core.serialization.unknown().optional(),
    org: core.serialization.unknown().optional(),
    team: core.serialization.unknown().optional(),
    division: core.serialization.unknown().optional(),
    partition: core.serialization.unknown().optional(),
    type: PostAggregationsRequestType.optional(),
    level: PostAggregationsRequestLevel.optional(),
    name: core.serialization.unknown().optional(),
    description: core.serialization.unknown().optional(),
    resource: core.serialization.number(),
    search: core.serialization.unknown(),
    totals: core.serialization.unknown(),
    degrouping: core.serialization.unknown().optional(),
    status: PostAggregationsRequestStatus,
    schedule: PostAggregationsRequestSchedule,
    scheduleFactor: core.serialization.unknown(),
    start: core.serialization.unknown(),
    default: PostAggregationsRequestDefault,
    inactive: PostAggregationsRequestInactive,
    frozen: PostAggregationsRequestFrozen,
});

export declare namespace PostAggregationsRequest {
    interface Raw {
        login?: unknown;
        entity?: unknown | null;
        forlogin?: unknown | null;
        org?: unknown | null;
        team?: unknown | null;
        division?: unknown | null;
        partition?: unknown | null;
        type?: PostAggregationsRequestType.Raw | null;
        level?: PostAggregationsRequestLevel.Raw | null;
        name?: unknown | null;
        description?: unknown | null;
        resource: number;
        search?: unknown;
        totals?: unknown;
        degrouping?: unknown | null;
        status: PostAggregationsRequestStatus.Raw;
        schedule: PostAggregationsRequestSchedule.Raw;
        scheduleFactor?: unknown;
        start?: unknown;
        default: PostAggregationsRequestDefault.Raw;
        inactive: PostAggregationsRequestInactive.Raw;
        frozen: PostAggregationsRequestFrozen.Raw;
    }
}
