/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetCredentialsResponseResponseDetails } from "./GetCredentialsResponseResponseDetails";

export const GetCredentialsResponseResponse: core.serialization.ObjectSchema<
    serializers.GetCredentialsResponseResponse.Raw,
    ButtonclikrApi.GetCredentialsResponseResponse
> = core.serialization.object({
    data: core.serialization.unknown().optional(),
    details: GetCredentialsResponseResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetCredentialsResponseResponse {
    interface Raw {
        data?: unknown | null;
        details?: GetCredentialsResponseResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
