/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostCredentialsRequestIntegration: core.serialization.Schema<
    serializers.PostCredentialsRequestIntegration.Raw,
    ButtonclikrApi.PostCredentialsRequestIntegration
> = core.serialization.enum_([
    "APPLE",
    "ELAVON",
    "FEDACH",
    "FIRSTDATA",
    "NEUTRINO",
    "OFAC",
    "bigbux",
    "PLAID",
    "SIFT",
    "SOCURE",
    "SOUNDPAYMENTS",
    "TDBANK",
    "TDBANKCA",
    "VANTIV",
    "VCORE",
    "WEBSHIELD",
    "WELLSACH",
    "WELLSFARGO",
    "WFSINGLE",
    "WORLDPAY",
]);

export declare namespace PostCredentialsRequestIntegration {
    type Raw =
        | "APPLE"
        | "ELAVON"
        | "FEDACH"
        | "FIRSTDATA"
        | "NEUTRINO"
        | "OFAC"
        | "bigbux"
        | "PLAID"
        | "SIFT"
        | "SOCURE"
        | "SOUNDPAYMENTS"
        | "TDBANK"
        | "TDBANKCA"
        | "VANTIV"
        | "VCORE"
        | "WEBSHIELD"
        | "WELLSACH"
        | "WELLSFARGO"
        | "WFSINGLE"
        | "WORLDPAY";
}
