/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetAlertsResponseResponse } from "./GetAlertsResponseResponse";
import { GetAlertsResponseDetails } from "./GetAlertsResponseDetails";

export const GetAlertsResponse: core.serialization.ObjectSchema<
    serializers.GetAlertsResponse.Raw,
    ButtonclikrApi.GetAlertsResponse
> = core.serialization.object({
    response: GetAlertsResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: GetAlertsResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetAlertsResponse {
    interface Raw {
        response?: GetAlertsResponseResponse.Raw | null;
        data?: unknown | null;
        details?: GetAlertsResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
