/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutAlertsIdResponseDetailsPage } from "./PutAlertsIdResponseDetailsPage";

export const PutAlertsIdResponseDetails: core.serialization.ObjectSchema<
    serializers.PutAlertsIdResponseDetails.Raw,
    ButtonclikrApi.PutAlertsIdResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: PutAlertsIdResponseDetailsPage.optional(),
});

export declare namespace PutAlertsIdResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: PutAlertsIdResponseDetailsPage.Raw | null;
    }
}
