/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ButtonclikrApi from "../../../../index";

/**
 * @example
 *     {
 *         login: {
 *             "key": "value"
 *         },
 *         partition: {
 *             "key": "value"
 *         },
 *         division: {
 *             "key": "value"
 *         },
 *         org: {
 *             "key": "value"
 *         },
 *         entity: {
 *             "key": "value"
 *         },
 *         mcc: ButtonclikrApi.PutMccsIdRequestMcc.SevenHundredFortyTwo,
 *         type: ButtonclikrApi.PutMccsIdRequestType.Blacklist
 *     }
 */
export interface PutMccsIdRequest {
    login?: unknown;
    partition?: unknown;
    division?: unknown;
    org?: unknown;
    entity?: unknown;
    mcc: ButtonclikrApi.PutMccsIdRequestMcc;
    /** Type. Indicates if the Mcc is blacklisted/whitelisted */
    type: ButtonclikrApi.PutMccsIdRequestType;
}
