/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetChargebackDocumentsIdResponseDetailsPage } from "./GetChargebackDocumentsIdResponseDetailsPage";

export const GetChargebackDocumentsIdResponseDetails: core.serialization.ObjectSchema<
    serializers.GetChargebackDocumentsIdResponseDetails.Raw,
    ButtonclikrApi.GetChargebackDocumentsIdResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetChargebackDocumentsIdResponseDetailsPage.optional(),
});

export declare namespace GetChargebackDocumentsIdResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetChargebackDocumentsIdResponseDetailsPage.Raw | null;
    }
}
