/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetChargebackMessagesResponseDetailsPage } from "./GetChargebackMessagesResponseDetailsPage";

export const GetChargebackMessagesResponseDetails: core.serialization.ObjectSchema<
    serializers.GetChargebackMessagesResponseDetails.Raw,
    ButtonclikrApi.GetChargebackMessagesResponseDetails
> = core.serialization.object({
    requestId: core.serialization.unknown().optional(),
    page: GetChargebackMessagesResponseDetailsPage.optional(),
});

export declare namespace GetChargebackMessagesResponseDetails {
    interface Raw {
        requestId?: unknown | null;
        page?: GetChargebackMessagesResponseDetailsPage.Raw | null;
    }
}
