/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetChargebackDocumentsIdResponseResponse } from "./GetChargebackDocumentsIdResponseResponse";
import { GetChargebackDocumentsIdResponseDetails } from "./GetChargebackDocumentsIdResponseDetails";

export const GetChargebackDocumentsIdResponse: core.serialization.ObjectSchema<
    serializers.GetChargebackDocumentsIdResponse.Raw,
    ButtonclikrApi.GetChargebackDocumentsIdResponse
> = core.serialization.object({
    response: GetChargebackDocumentsIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: GetChargebackDocumentsIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetChargebackDocumentsIdResponse {
    interface Raw {
        response?: GetChargebackDocumentsIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: GetChargebackDocumentsIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
