/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetChargebacksResponseResponse } from "./GetChargebacksResponseResponse";
import { GetChargebacksResponseDetails } from "./GetChargebacksResponseDetails";

export const GetChargebacksResponse: core.serialization.ObjectSchema<
    serializers.GetChargebacksResponse.Raw,
    ButtonclikrApi.GetChargebacksResponse
> = core.serialization.object({
    response: GetChargebacksResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: GetChargebacksResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace GetChargebacksResponse {
    interface Raw {
        response?: GetChargebacksResponseResponse.Raw | null;
        data?: unknown | null;
        details?: GetChargebacksResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
