/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { PutChargebackDocumentsIdResponseResponse } from "./PutChargebackDocumentsIdResponseResponse";
import { PutChargebackDocumentsIdResponseDetails } from "./PutChargebackDocumentsIdResponseDetails";

export const PutChargebackDocumentsIdResponse: core.serialization.ObjectSchema<
    serializers.PutChargebackDocumentsIdResponse.Raw,
    ButtonclikrApi.PutChargebackDocumentsIdResponse
> = core.serialization.object({
    response: PutChargebackDocumentsIdResponseResponse.optional(),
    data: core.serialization.unknown().optional(),
    details: PutChargebackDocumentsIdResponseDetails.optional(),
    errors: core.serialization.unknown().optional(),
});

export declare namespace PutChargebackDocumentsIdResponse {
    interface Raw {
        response?: PutChargebackDocumentsIdResponseResponse.Raw | null;
        data?: unknown | null;
        details?: PutChargebackDocumentsIdResponseDetails.Raw | null;
        errors?: unknown | null;
    }
}
