/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";

export const PutChargebacksIdRequestShadow: core.serialization.Schema<
    serializers.PutChargebacksIdRequestShadow.Raw,
    ButtonclikrApi.PutChargebacksIdRequestShadow
> = core.serialization.enum_(["0", "1"]);

export declare namespace PutChargebacksIdRequestShadow {
    type Raw = "0" | "1";
}
