/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ButtonclikrApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { PutPlansIdRequestUm } from "../../types/PutPlansIdRequestUm";
import { PutPlansIdRequestInactive } from "../../types/PutPlansIdRequestInactive";
import { PutPlansIdRequestFrozen } from "../../types/PutPlansIdRequestFrozen";

export const PutPlansIdRequest: core.serialization.Schema<
    serializers.PutPlansIdRequest.Raw,
    ButtonclikrApi.PutPlansIdRequest
> = core.serialization.object({
    amount: core.serialization.unknown(),
    billing: core.serialization.unknown().optional(),
    order: core.serialization.unknown().optional(),
    txnDescription: core.serialization.unknown().optional(),
    description: core.serialization.unknown().optional(),
    maxFailures: core.serialization.unknown().optional(),
    name: core.serialization.unknown().optional(),
    schedule: core.serialization.string(),
    scheduleFactor: core.serialization.unknown(),
    um: PutPlansIdRequestUm,
    inactive: PutPlansIdRequestInactive,
    frozen: PutPlansIdRequestFrozen,
});

export declare namespace PutPlansIdRequest {
    interface Raw {
        amount?: unknown;
        billing?: unknown | null;
        order?: unknown | null;
        txnDescription?: unknown | null;
        description?: unknown | null;
        maxFailures?: unknown | null;
        name?: unknown | null;
        schedule: string;
        scheduleFactor?: unknown;
        um: PutPlansIdRequestUm.Raw;
        inactive: PutPlansIdRequestInactive.Raw;
        frozen: PutPlansIdRequestFrozen.Raw;
    }
}
