/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ButtonclikrApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { PostMfaRecoveryCodesRequestUsed } from "../../types/PostMfaRecoveryCodesRequestUsed";

export const PostMfaRecoveryCodesRequest: core.serialization.Schema<
    serializers.PostMfaRecoveryCodesRequest.Raw,
    ButtonclikrApi.PostMfaRecoveryCodesRequest
> = core.serialization.object({
    login: core.serialization.unknown(),
    code: core.serialization.unknown(),
    used: PostMfaRecoveryCodesRequestUsed,
});

export declare namespace PostMfaRecoveryCodesRequest {
    interface Raw {
        login?: unknown;
        code?: unknown;
        used: PostMfaRecoveryCodesRequestUsed.Raw;
    }
}
