/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ButtonclikrApi from "../../../../api/index";
import * as core from "../../../../core";
import { DeleteAccountRefsIdResponseResponse } from "./DeleteAccountRefsIdResponseResponse";

export const DeleteAccountRefsIdResponse: core.serialization.ObjectSchema<
    serializers.DeleteAccountRefsIdResponse.Raw,
    ButtonclikrApi.DeleteAccountRefsIdResponse
> = core.serialization.object({
    response: DeleteAccountRefsIdResponseResponse.optional(),
});

export declare namespace DeleteAccountRefsIdResponse {
    interface Raw {
        response?: DeleteAccountRefsIdResponseResponse.Raw | null;
    }
}
